//! Z0a2 run goldens: the behavior baseline of the simplification pass (SIMPLIFY.md §3),
//! characterized on main 5c787b7 with fake-leapp through the stable entry points
//! (`runner::start`, `RunJob::prepare` + `PreparedRun::run`, the contract types).
//!
//! - A normalized golden `run.json` for every CONTRACTS.md §7.4 row (`slow` and `ignore_term`
//!   cancelled on the first log batch; `ignore_term` on Unix only), `glibc_too_old` for iLEAPP and
//!   aLEAPP, an aLEAPP `success`, a hashed single-file input, an iLEAPP `itunes` run with a
//!   password (the redacted argv, with a keychain, custom modules and an explicit timezone),
//!   `prepare_failed` and a seal that fails (E2).
//! - The initial `run.json` (read right after `RunJob::prepare`) of four of them.
//! - The normalized `report.sha256` of every run that sealed a report.
//! - The `run_start` refusals: `password_required` and the argv path check (E7), each an exact
//!   `AppError` that creates no run folder; an unreadable keychain (E14, Unix).
//!
//! **Comparison.** JSON is compared as text (the file as written), so key order, nulls, messages
//! and argv are exact. Normalization replaces only run-specific values, each by a token:
//! - strings: the lab folder (`<LAB>`: the case, the input, the app cache), fake-leapp's absolute
//!   path (`<FAKE_LEAPP>`), the run id (`<RUN_ID>`), the case id (`<CASE_ID>`), fake-leapp's
//!   SHA-256 (`<FAKE_LEAPP_SHA256>`, checked against `sha2` over the binary), the hash of
//!   `report.sha256` (`<MANIFEST_SHA256>`, checked against `sha2` over the file; the manifest lists
//!   `_lava_data.lava`, which holds absolute paths and a timestamp), fake-leapp's process id in
//!   the glibc loader line (`PYI-<PID>:`, `_MEIfake<PID>`), timestamps (`<TIMESTAMP>`, only strings
//!   in the RFC 3339 `Z` format) and `app.version` (`<APP_VERSION>`);
//! - `tool.platform` (`<PLATFORM>`, only when it is this host's platform key);
//! - `output.seal.total_bytes` (`<TOTAL_BYTES>`, only when it equals the size of the files that
//!   `report.sha256` lists, read from disk: `_lava_data.lava` and, in the cancel rows, the partial
//!   `Screen_Output.html` vary);
//! - `duration_ms` (`<DURATION_MS>`, any integer, also checked against `ended_at − created_at`;
//!   `null` stays).
//!
//! The host is fixed by the test. In `report.sha256` every hash is checked against `sha2` over
//! its file and then replaced by `<SHA256>`; names, order and line format stay exact, and the
//! manifest must list exactly the regular files under `report/`.
//!
//! **Goldens** live in `tests/golden/run/`. A file under `tests/golden/run/<os>/` (`windows`,
//! `linux`) replaces the default (macOS) one on that OS. On a mismatch the normalized actual is
//! printed and written to `<CARGO_TARGET_TMPDIR>/z0a2-actual/<os>/`.
//!
//! Frozen: later bundles do not edit this file or its goldens (SIMPLIFY.md §2).

use std::ffi::OsString;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use serde::Serialize;
use sha2::{Digest, Sha256};

use suitedfir_core::case::{self, CreatedCase};
use suitedfir_core::contracts::{
    AppError, InputType, ModuleSelection, RecordHost, RunEvent, RunPhase, RunRecord, RunRequest,
    RunStatus, Seal, SealStatus, Settings, ToolId, examples, parse_versioned,
};
use suitedfir_core::manifest;
use suitedfir_core::paths::AppPaths;
use suitedfir_core::runner::{self, RunContext, RunJob, RunOutcome};
use suitedfir_core::settings;

const FAKE_LEAPP: &str = env!("CARGO_BIN_EXE_fake-leapp");
const GOLDEN_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/run");
const APP_VERSION: &str = env!("CARGO_PKG_VERSION");
const PASSWORD: &str = "z0a2-Backup-Pw!";

// ---- goldens ----

fn os_name() -> &'static str {
    if cfg!(windows) {
        "windows"
    } else if cfg!(target_os = "linux") {
        "linux"
    } else {
        "macos"
    }
}

/// The golden checks of one test: every mismatch is printed (normalized actual) and saved, and
/// the test fails at [`Goldens::finish`].
#[derive(Default)]
struct Goldens {
    mismatches: Vec<String>,
}

impl Goldens {
    /// The golden file of `name` on this OS: the per-OS one if it exists, else the default.
    fn file(name: &str) -> PathBuf {
        let os_file = Path::new(GOLDEN_DIR).join(os_name()).join(name);
        if os_file.is_file() {
            os_file
        } else {
            Path::new(GOLDEN_DIR).join(name)
        }
    }

    fn check(&mut self, name: &str, actual: &str) {
        let file = Self::file(name);
        let expected = fs::read_to_string(&file).ok();
        if expected.as_deref() == Some(actual) {
            return;
        }
        let saved = Path::new(env!("CARGO_TARGET_TMPDIR"))
            .join("z0a2-actual")
            .join(os_name())
            .join(name);
        let _ = fs::create_dir_all(saved.parent().unwrap());
        let _ = fs::write(&saved, actual);
        eprintln!(
            "---- z0a2 golden mismatch: {name} on {} (golden {}{}; actual saved to {}) ----\n\
             {actual}\n---- end of {name} ----",
            os_name(),
            file.display(),
            if expected.is_none() { ", missing" } else { "" },
            saved.display()
        );
        self.mismatches.push(name.to_owned());
    }

    fn finish(self) {
        assert!(
            self.mismatches.is_empty(),
            "golden mismatches on {} (normalized actuals printed above): {:?}",
            os_name(),
            self.mismatches
        );
    }
}

// ---- normalization ----

/// `text` as it appears inside a JSON string.
fn escaped(text: &str) -> String {
    let quoted = serde_json::to_string(text).unwrap();
    quoted[1..quoted.len() - 1].to_owned()
}

/// `YYYY-MM-DDTHH:MM:SSZ`.
fn is_timestamp(text: &str) -> bool {
    let bytes = text.as_bytes();
    bytes.len() == 20
        && bytes.iter().enumerate().all(|(i, b)| match i {
            4 | 7 => *b == b'-',
            10 => *b == b'T',
            13 | 16 => *b == b':',
            19 => *b == b'Z',
            _ => b.is_ascii_digit(),
        })
}

/// The end (exclusive) of the JSON string starting at `start` (its opening quote).
fn string_end(bytes: &[u8], start: usize) -> usize {
    let mut i = start + 1;
    loop {
        match bytes[i] {
            b'\\' => i += 2,
            b'"' => return i + 1,
            _ => i += 1,
        }
    }
}

/// Lowercase hex SHA-256, computed here with `sha2` (never through the code under test).
fn sha256_hex(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

/// Normalizes JSON text (see the module doc).
struct Normalizer {
    /// Run-specific strings, JSON-escaped, and their tokens; applied in order.
    subs: Vec<(String, &'static str)>,
    /// `(parent key, key, raw JSON value, token)`: exactly that value at that place becomes the
    /// token (a JSON string).
    values: Vec<(&'static str, &'static str, String, &'static str)>,
}

impl Normalizer {
    fn new() -> Self {
        Self {
            subs: Vec::new(),
            values: Vec::new(),
        }
    }

    fn sub(&mut self, text: &str, token: &'static str) -> &mut Self {
        self.subs.push((escaped(text), token));
        self
    }

    fn value(&mut self, parent: &'static str, key: &'static str, raw: String, token: &'static str) {
        self.values.push((parent, key, raw, token));
    }

    fn normalize(&self, path: &[String], raw: &str) -> String {
        let key = path.last().map_or("", String::as_str);
        let parent = path.len().checked_sub(2).map_or("", |i| path[i].as_str());
        if key == "duration_ms" {
            return if raw.parse::<u64>().is_ok() {
                "\"<DURATION_MS>\"".to_owned()
            } else {
                raw.to_owned()
            };
        }
        for (p, k, value, token) in &self.values {
            if *p == parent && *k == key && value == raw {
                return format!("\"{token}\"");
            }
        }
        if !raw.starts_with('"') {
            return raw.to_owned();
        }
        if parent == "app" && key == "version" && raw == format!("\"{APP_VERSION}\"") {
            return "\"<APP_VERSION>\"".to_owned();
        }
        let mut text = raw.to_owned();
        for (from, to) in &self.subs {
            text = text.replace(from.as_str(), to);
        }
        if is_timestamp(&text[1..text.len() - 1]) {
            return "\"<TIMESTAMP>\"".to_owned();
        }
        text
    }

    /// Normalizes JSON text, keeping everything else (layout, key order) byte for byte.
    fn json(&self, text: &str) -> String {
        let bytes = text.as_bytes();
        let mut out = String::with_capacity(text.len());
        // The key of each open object (`[]` for arrays), and whether a key comes next.
        let mut path: Vec<String> = Vec::new();
        let mut objects: Vec<bool> = Vec::new();
        let mut want_key = false;
        let mut i = 0;
        while i < bytes.len() {
            match bytes[i] {
                b'{' | b'[' => {
                    let object = bytes[i] == b'{';
                    objects.push(object);
                    path.push(if object {
                        String::new()
                    } else {
                        "[]".to_owned()
                    });
                    want_key = object;
                    out.push(char::from(bytes[i]));
                    i += 1;
                }
                b'}' | b']' => {
                    objects.pop();
                    path.pop();
                    want_key = false;
                    out.push(char::from(bytes[i]));
                    i += 1;
                }
                b',' => {
                    want_key = objects.last() == Some(&true);
                    out.push(',');
                    i += 1;
                }
                b'"' => {
                    let end = string_end(bytes, i);
                    let raw = &text[i..end];
                    if want_key {
                        *path.last_mut().unwrap() = serde_json::from_str(raw).unwrap();
                        want_key = false;
                        out.push_str(raw);
                    } else {
                        out.push_str(&self.normalize(&path, raw));
                    }
                    i = end;
                }
                b':' | b' ' | b'\n' | b'\r' | b'\t' => {
                    out.push(char::from(bytes[i]));
                    i += 1;
                }
                _ => {
                    let end = bytes[i..]
                        .iter()
                        .position(|b| matches!(b, b',' | b'}' | b']') || b.is_ascii_whitespace())
                        .map_or(bytes.len(), |n| i + n);
                    out.push_str(&self.normalize(&path, &text[i..end]));
                    i = end;
                }
            }
        }
        out
    }
}

fn pretty<T: Serialize>(value: &T) -> String {
    let mut text = serde_json::to_string_pretty(value).unwrap();
    text.push('\n');
    text
}

// ---- the lab ----

/// The host the records name (fixed, so no golden depends on the machine).
fn host() -> RecordHost {
    RecordHost {
        os: "testos".to_owned(),
        os_version: "1.0".to_owned(),
        arch: "testarch".to_owned(),
        hostname: "LAB-TEST-01".to_owned(),
    }
}

/// App dirs, a known case and an `fs` input folder, all in a short-named temp dir (the Windows test
/// machine has long paths disabled).
struct Lab {
    root: tempfile::TempDir,
    paths: AppPaths,
    settings: Settings,
    case: CreatedCase,
    input: PathBuf,
}

impl Lab {
    fn new() -> Self {
        let root = tempfile::Builder::new().prefix("sdz").tempdir().unwrap();
        let paths = AppPaths {
            app_data: root.path().join("data"),
            app_config: root.path().join("config"),
            app_cache: root.path().join("cache"),
            app_log: root.path().join("log"),
        };
        let cases = root.path().join("cases");
        fs::create_dir_all(&cases).unwrap();
        let case = case::create(&cases, &examples::case_fields()).unwrap();
        let mut settings = settings::defaults(&cases);
        settings::touch_recent(&mut settings, &case.path.to_string_lossy());
        let input = root.path().join("ev").join("fs");
        fs::create_dir_all(&input).unwrap();
        fs::write(input.join("evidence.txt"), "evidence").unwrap();
        Self {
            root,
            paths,
            settings,
            case,
            input,
        }
    }

    /// fake-leapp as the dev-override `tool`, in `scenario`, 20 lines 5 ms apart.
    fn context(&self, tool: ToolId, scenario: &str) -> RunContext {
        let manifest = &manifest::embedded().unwrap().tools[&tool];
        let prepared = runner::dev_override_tool(
            Path::new(FAKE_LEAPP),
            tool,
            manifest,
            manifest::host_platform(),
        )
        .unwrap();
        let env: Vec<(OsString, OsString)> = vec![
            ("FAKE_LEAPP_SCENARIO".into(), scenario.into()),
            ("FAKE_LEAPP_INTERVAL_MS".into(), "5".into()),
            ("FAKE_LEAPP_LINES".into(), "20".into()),
        ];
        RunContext {
            paths: self.paths.clone(),
            settings: self.settings.clone(),
            case_dir: self.case.path.clone(),
            case: self.case.case.clone(),
            host: host(),
            tool: prepared,
            env,
            max_run_dir_chars: runner::default_run_dir_limit(),
        }
    }

    fn request(&self, tool: ToolId, input: &Path, input_type: InputType) -> RunRequest {
        RunRequest {
            case_path: self.case.path.to_string_lossy().into_owned(),
            tool,
            input_path: input.to_string_lossy().into_owned(),
            input_type,
            modules: ModuleSelection::All,
            timezone: None,
            itunes_password: None,
            keychain_path: None,
            hash_input: false,
            label: Some("Golden run".to_owned()),
        }
    }

    fn fs_request(&self, tool: ToolId) -> RunRequest {
        self.request(tool, &self.input, InputType::Fs)
    }

    /// The case's run folders.
    fn run_dirs(&self) -> Vec<PathBuf> {
        fs::read_dir(self.case.path.join("runs"))
            .map(|entries| entries.map(|e| e.unwrap().path()).collect())
            .unwrap_or_default()
    }

    /// An iTunes-style backup folder at `dir` (`Manifest.plist` with `IsEncrypted`).
    fn itunes_backup(&self, dir: &Path, encrypted: bool) {
        fs::create_dir_all(dir).unwrap();
        let plist = format!(
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<plist version=\"1.0\"><dict>\
             <key>IsEncrypted</key><{encrypted}/></dict></plist>\n"
        );
        fs::write(dir.join("Manifest.plist"), plist).unwrap();
        fs::write(dir.join("Manifest.db"), b"SQLite format 3\0").unwrap();
    }

    /// A file input `image.zip` with fixed contents (detected as `zip`).
    fn file_input(&self) -> PathBuf {
        let path = self.root.path().join("ev").join("image.zip");
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, FILE_INPUT.repeat(1000)).unwrap();
        path
    }

    /// No per-run temp dir is left in `<app_cache>/tmp`.
    fn assert_no_temp_dirs(&self) {
        let left: Vec<_> = fs::read_dir(self.paths.temp_root())
            .map(|entries| entries.map(|e| e.unwrap().file_name()).collect())
            .unwrap_or_default();
        assert!(left.is_empty(), "left in the temp root: {left:?}");
    }
}

/// The hashed file input is this, 1000 times.
const FILE_INPUT: &[u8] = b"Z0a2 file input\n";

/// A run that went to its end.
struct Ran {
    outcome: RunOutcome,
    /// `run.json` right after `RunJob::prepare` (lifecycle step 2).
    initial: Option<String>,
    /// LEAPP's process id (the bootloader's), from the `running` phase on.
    pid: Option<u32>,
}

/// Runs a started job to the end: step 2 (`prepare`), then the rest. With `cancel`, the run is
/// cancelled when the first log batch arrives.
fn finish_job(job: RunJob, cancel: bool) -> Ran {
    let run_dir = job.run_dir().to_path_buf();
    let control = job.control();
    let mut pid = None;
    let mut cancelled = false;
    let mut emit = |event: RunEvent| match event {
        RunEvent::Phase {
            phase: RunPhase::Running,
        } => pid = control.process_id(),
        RunEvent::Log { .. } if cancel && !cancelled => {
            cancelled = true;
            control.cancel();
        }
        _ => {}
    };
    let prepared = job.prepare(&mut emit);
    let initial = fs::read_to_string(run_dir.join("run.json")).ok();
    let outcome = prepared.run(&mut emit);
    assert_eq!(cancelled, cancel, "the cancel was requested");
    assert_eq!(outcome.write_error, None);
    Ran {
        outcome,
        initial,
        pid,
    }
}

fn run(lab: &Lab, tool: ToolId, scenario: &str, request: RunRequest, cancel: bool) -> Ran {
    let job = runner::start(request, lab.context(tool, scenario)).unwrap();
    finish_job(job, cancel)
}

fn run_dir(ran: &Ran) -> PathBuf {
    PathBuf::from(&ran.outcome.summary.run_dir)
}

/// A seal without a manifest.
fn unsealed(status: SealStatus) -> Seal {
    Seal {
        status,
        manifest: None,
        manifest_sha256: None,
        file_count: None,
        total_bytes: None,
    }
}

/// Whether `id` is `YYYYMMDD-HHMMSSZ-<tool>-<6 lowercase hex>` stamped at `created_at`.
fn assert_run_id(id: &str, tool: ToolId, created_at: &str) {
    let stamp: String = created_at.chars().filter(|c| c.is_ascii_digit()).collect();
    let expected_prefix = format!("{}-{}Z-{tool}-", &stamp[..8], &stamp[8..]);
    let random = id.strip_prefix(&expected_prefix).unwrap_or_else(|| {
        panic!("run id {id} does not start with {expected_prefix}");
    });
    assert!(
        random.len() == 6
            && random
                .bytes()
                .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b)),
        "{id}"
    );
}

/// The regular files under `dir`, relative to `base` with `/` separators.
fn regular_files(base: &Path, dir: &Path) -> Vec<String> {
    let mut files = Vec::new();
    let mut pending = vec![dir.to_path_buf()];
    while let Some(folder) = pending.pop() {
        for entry in fs::read_dir(&folder).unwrap() {
            let path = entry.unwrap().path();
            let meta = fs::symlink_metadata(&path).unwrap();
            if meta.is_dir() {
                pending.push(path);
            } else if meta.is_file() {
                let rel = path.strip_prefix(base).unwrap();
                let parts: Vec<String> = rel
                    .components()
                    .map(|c| c.as_os_str().to_string_lossy().into_owned())
                    .collect();
                files.push(parts.join("/"));
            }
        }
    }
    files.sort();
    files
}

/// A manifest path as written (GNU `sha256sum` escaping undone).
fn unescape(name: &str) -> String {
    let mut out = String::new();
    let mut chars = name.chars();
    while let Some(c) = chars.next() {
        if c == '\\' {
            match chars.next() {
                Some('\\') => out.push('\\'),
                Some('n') => out.push('\n'),
                Some('r') => out.push('\r'),
                other => panic!("bad escape {other:?} in {name:?}"),
            }
        } else {
            out.push(c);
        }
    }
    out
}

/// What the check of `report.sha256` found.
struct Manifest {
    /// SHA-256 of the manifest file.
    sha256: String,
    /// Bytes of the files it lists, read from disk.
    total_bytes: u64,
    lines: u64,
}

/// Checks `report.sha256` (when the run wrote one): every line's hash against `sha2` over its
/// file, exactly the regular files under `report/` listed; then its golden with the hashes
/// replaced. A manifest must be written exactly when its golden exists.
fn check_manifest(goldens: &mut Goldens, name: &str, dir: &Path) -> Option<Manifest> {
    let golden = format!("{name}.report.sha256");
    let bytes = match fs::read(dir.join("report.sha256")) {
        Ok(bytes) => bytes,
        Err(e) if e.kind() == io::ErrorKind::NotFound => {
            if Goldens::file(&golden).is_file() {
                eprintln!(
                    "---- z0a2 golden mismatch: {golden} on {}: the golden exists, but no \
                     report.sha256 was written ----",
                    os_name()
                );
                goldens.mismatches.push(golden);
            }
            return None;
        }
        Err(e) => panic!("report.sha256: {e}"),
    };
    let text = String::from_utf8(bytes.clone()).unwrap();
    let mut normalized = String::new();
    let mut listed = Vec::new();
    let mut total_bytes = 0u64;
    for line in text.split_inclusive('\n') {
        let body = line.strip_suffix('\n').expect("LF line endings");
        let (prefix, rest) = match body.strip_prefix('\\') {
            Some(rest) => ("\\", rest),
            None => ("", body),
        };
        let (hash, name_part) = rest.split_at(64);
        let written = name_part.strip_prefix("  ").expect("two spaces");
        let rel = if prefix.is_empty() {
            written.to_owned()
        } else {
            unescape(written)
        };
        let file = rel
            .split('/')
            .fold(dir.to_path_buf(), |path, part| path.join(part));
        let contents = fs::read(&file).unwrap();
        assert_eq!(hash, sha256_hex(&contents), "{rel}");
        total_bytes += contents.len() as u64;
        listed.push(rel);
        normalized.push_str(prefix);
        normalized.push_str("<SHA256>  ");
        normalized.push_str(written);
        normalized.push('\n');
    }
    let mut sorted = listed.clone();
    sorted.sort();
    assert_eq!(sorted, regular_files(dir, &dir.join("report")));
    goldens.check(&golden, &normalized);
    Some(Manifest {
        sha256: sha256_hex(&bytes),
        total_bytes,
        lines: listed.len() as u64,
    })
}

/// The normalizer for the records of `ran` in `lab` (see the module doc).
fn normalizer(lab: &Lab, ran: &Ran, manifest: Option<&Manifest>) -> Normalizer {
    let mut normalizer = Normalizer::new();
    let fake = std::path::absolute(FAKE_LEAPP).unwrap();
    normalizer
        .sub(&fake.to_string_lossy(), "<FAKE_LEAPP>")
        .sub(&lab.root.path().to_string_lossy(), "<LAB>")
        .sub(&ran.outcome.record.run_id, "<RUN_ID>")
        .sub(&lab.case.case.case_id, "<CASE_ID>")
        .sub(
            &sha256_hex(&fs::read(FAKE_LEAPP).unwrap()),
            "<FAKE_LEAPP_SHA256>",
        );
    if let Some(manifest) = manifest {
        normalizer.sub(&manifest.sha256, "<MANIFEST_SHA256>");
        normalizer.value(
            "seal",
            "total_bytes",
            manifest.total_bytes.to_string(),
            "<TOTAL_BYTES>",
        );
    }
    if let Some(pid) = ran.pid {
        normalizer
            .sub(&format!("PYI-{pid}:"), "PYI-<PID>:")
            .sub(&format!("_MEIfake{pid}"), "_MEIfake<PID>");
    }
    if let Some(platform) = manifest::host_platform() {
        normalizer.value(
            "tool",
            "platform",
            serde_json::to_string(&platform).unwrap(),
            "<PLATFORM>",
        );
    }
    normalizer
}

/// The goldens of one run: `<name>.run.json`, `<name>.report.sha256` (exactly when a report was
/// sealed; with `manifest` false, `report.sha256` is not a manifest of this run) and, with
/// `initial`, `<name>.initial.run.json`. Also: the record on disk is the outcome's, final and
/// read-only; its run id and duration fit its times; no temp dir is left.
fn check_run(
    goldens: &mut Goldens,
    name: &str,
    lab: &Lab,
    ran: &Ran,
    manifest: bool,
    initial: bool,
) {
    let dir = run_dir(ran);
    let record = &ran.outcome.record;
    let found = if manifest {
        check_manifest(goldens, name, &dir)
    } else {
        None
    };
    if let Some(found) = &found {
        assert_eq!(record.output.seal.file_count, Some(found.lines));
    }
    let text = fs::read_to_string(dir.join("run.json")).unwrap();
    let on_disk: RunRecord = parse_versioned(text.as_bytes()).unwrap();
    assert_eq!(&on_disk, record);
    assert!(
        fs::metadata(dir.join("run.json"))
            .unwrap()
            .permissions()
            .readonly()
    );
    assert_eq!(dir.file_name().unwrap().to_string_lossy(), record.run_id);
    assert_run_id(
        &record.run_id,
        record.tool.id,
        &record.created_at.to_string(),
    );
    let ended = record.ended_at.expect("finalized").as_datetime();
    let expected_ms = (ended - record.created_at.as_datetime()).whole_milliseconds();
    assert_eq!(record.duration_ms.map(i128::from), Some(expected_ms));
    let normalizer = normalizer(lab, ran, found.as_ref());
    goldens.check(&format!("{name}.run.json"), &normalizer.json(&text));
    if initial {
        let text = ran.initial.as_deref().expect("the initial run.json");
        let first: RunRecord = parse_versioned(text.as_bytes()).unwrap();
        assert_eq!(first.status, RunStatus::Running);
        assert_eq!(first.output.seal, unsealed(SealStatus::Pending));
        goldens.check(&format!("{name}.initial.run.json"), &normalizer.json(text));
    }
    lab.assert_no_temp_dirs();
}

/// Run-folder files written in lifecycle step 2 (`case.lcasedata`, `profile.<ext>`), pinned byte
/// for byte as `<name>.<file>` (their contents hold no run-specific value).
fn check_files(goldens: &mut Goldens, name: &str, ran: &Ran, files: &[&str]) {
    for file in files {
        let text = fs::read_to_string(run_dir(ran).join(file)).unwrap();
        goldens.check(&format!("{name}.{file}"), &text);
    }
}

/// One row with the lab's `fs` input.
fn row(name: &str, tool: ToolId, scenario: &str, cancel: bool) -> RunRecord {
    let lab = Lab::new();
    let ran = run(&lab, tool, scenario, lab.fs_request(tool), cancel);
    let mut goldens = Goldens::default();
    check_run(&mut goldens, name, &lab, &ran, true, false);
    goldens.finish();
    ran.outcome.record
}

// ---- CONTRACTS.md §7.4 ----

/// Also the initial record and `case.lcasedata`; mode `all` writes no profile.
#[test]
fn z0_success() {
    let lab = Lab::new();
    let ran = run(
        &lab,
        ToolId::Ileapp,
        "success",
        lab.fs_request(ToolId::Ileapp),
        false,
    );
    assert!(!run_dir(&ran).join("profile.ilprofile").exists());
    let mut goldens = Goldens::default();
    check_run(&mut goldens, "success", &lab, &ran, true, true);
    check_files(&mut goldens, "success", &ran, &["case.lcasedata"]);
    goldens.finish();
}

#[test]
fn z0_artifact_error() {
    row("artifact_error", ToolId::Ileapp, "artifact_error", false);
}

#[test]
fn z0_invalid_input() {
    row("invalid_input", ToolId::Ileapp, "invalid_input", false);
}

#[test]
fn z0_early_exit() {
    let record = row("early_exit", ToolId::Ileapp, "early_exit", false);
    assert_eq!(record.output.seal, unsealed(SealStatus::SkippedNoOutput));
}

#[test]
fn z0_argparse_error() {
    let record = row("argparse_error", ToolId::Ileapp, "argparse_error", false);
    assert_eq!(record.output.seal, unsealed(SealStatus::SkippedNoOutput));
}

#[test]
fn z0_crash() {
    row("crash", ToolId::Ileapp, "crash", false);
}

#[test]
fn z0_prompt() {
    row("prompt", ToolId::Ileapp, "prompt", false);
}

/// `slow` + cancel on the first log batch: SIGTERM on Unix; on Windows the job is terminated.
#[test]
fn z0_slow_cancel() {
    row("slow_cancel", ToolId::Ileapp, "slow", true);
}

/// `ignore_term` + cancel on the first log batch (Unix): SIGKILL after the 10 s grace.
#[cfg(unix)]
#[test]
fn z0_ignore_term_cancel() {
    row("ignore_term_cancel", ToolId::Ileapp, "ignore_term", true);
}

/// The loader of a pinned Linux build refuses a too-old glibc (LEAPP-CLI.md §2): `spawn_failed`
/// naming the tool and the glibc it needs, and no report.
fn glibc_row(name: &str, tool: ToolId) {
    let lab = Lab::new();
    let ran = run(&lab, tool, "glibc_too_old", lab.fs_request(tool), false);
    assert!(ran.pid.is_some(), "LEAPP was spawned");
    let mut goldens = Goldens::default();
    check_run(&mut goldens, name, &lab, &ran, true, tool == ToolId::Aleapp);
    goldens.finish();
    assert_eq!(
        ran.outcome.record.output.seal,
        unsealed(SealStatus::SkippedNoOutput)
    );
}

#[test]
fn z0_glibc_too_old_ileapp() {
    glibc_row("glibc_too_old_ileapp", ToolId::Ileapp);
}

/// Also pins aLEAPP's spelling of the glibc message (E15) and aLEAPP's initial record.
#[test]
fn z0_glibc_too_old_aleapp() {
    glibc_row("glibc_too_old_aleapp", ToolId::Aleapp);
}

#[test]
fn z0_success_aleapp() {
    row("success_aleapp", ToolId::Aleapp, "success", false);
}

// ---- inputs and options ----

/// A single-file input, hashed concurrently with LEAPP (the hash is of fixed contents, so it stays
/// exact in the golden).
#[test]
fn z0_hashed_file() {
    let lab = Lab::new();
    let input = lab.file_input();
    let mut request = lab.request(ToolId::Ileapp, &input, InputType::Zip);
    request.hash_input = true;
    let ran = run(&lab, ToolId::Ileapp, "success", request, false);
    let hash = &ran.outcome.record.input.hash;
    assert_eq!(
        hash.value.as_deref(),
        Some(sha256_hex(&FILE_INPUT.repeat(1000)).as_str())
    );
    let mut goldens = Goldens::default();
    check_run(&mut goldens, "hashed_file", &lab, &ran, true, true);
    goldens.finish();
}

/// An encrypted iTunes backup with its password, a keychain, custom modules and an explicit
/// timezone: the recorded argv has `<redacted>` after `--itunes_password`, and the password is in
/// no file of the run folder.
#[test]
fn z0_itunes_password() {
    let lab = Lab::new();
    let backup = lab.root.path().join("ev").join("bk");
    lab.itunes_backup(&backup, true);
    let keychain = lab.root.path().join("ev").join("keychain-2.db");
    fs::write(&keychain, b"keychain bytes").unwrap();
    let mut request = lab.request(ToolId::Ileapp, &backup, InputType::Itunes);
    request.itunes_password = Some(PASSWORD.to_owned());
    request.keychain_path = Some(keychain.to_string_lossy().into_owned());
    request.timezone = Some("Europe/Berlin".to_owned());
    request.modules = ModuleSelection::Custom {
        modules: vec!["sms".to_owned(), "callHistory".to_owned()],
    };
    let ran = run(&lab, ToolId::Ileapp, "success", request, false);
    assert_eq!(
        ran.outcome.record.options.keychain_sha256.as_deref(),
        Some(sha256_hex(b"keychain bytes").as_str())
    );
    let dir = run_dir(&ran);
    let mut pending = vec![dir.clone()];
    while let Some(folder) = pending.pop() {
        for entry in fs::read_dir(&folder).unwrap() {
            let path = entry.unwrap().path();
            if path.is_dir() {
                pending.push(path);
            } else {
                let bytes = fs::read(&path).unwrap();
                assert!(
                    !bytes
                        .windows(PASSWORD.len())
                        .any(|w| w == PASSWORD.as_bytes()),
                    "{} holds the password",
                    path.display()
                );
            }
        }
    }
    let mut goldens = Goldens::default();
    check_run(&mut goldens, "itunes_password", &lab, &ran, true, true);
    check_files(
        &mut goldens,
        "itunes_password",
        &ran,
        &["profile.ilprofile"],
    );
    goldens.finish();
}

// ---- prepare_failed and a failed seal ----

/// `<app_cache>/tmp` is a file, so the run's temp dir cannot be created (lifecycle step 2):
/// `prepare_failed`, and the requested input hash never started (`cancelled`).
#[test]
fn z0_prepare_failed() {
    let lab = Lab::new();
    fs::create_dir_all(&lab.paths.app_cache).unwrap();
    fs::write(lab.paths.temp_root(), "not a folder").unwrap();
    let input = lab.file_input();
    let mut request = lab.request(ToolId::Ileapp, &input, InputType::Zip);
    request.hash_input = true;
    let ran = run(&lab, ToolId::Ileapp, "success", request, false);
    fs::remove_file(lab.paths.temp_root()).unwrap();
    assert_eq!(
        ran.outcome.record.output.seal,
        unsealed(SealStatus::SkippedNoOutput)
    );
    let mut goldens = Goldens::default();
    check_run(&mut goldens, "prepare_failed", &lab, &ran, true, false);
    goldens.finish();
}

/// A `report.sha256` that is already in the run folder: `seal_tree` refuses to replace it, so the
/// seal fails (E2) and the file is left as it was.
#[test]
fn z0_seal_failed() {
    let lab = Lab::new();
    let job = runner::start(
        lab.fs_request(ToolId::Ileapp),
        lab.context(ToolId::Ileapp, "success"),
    )
    .unwrap();
    let existing = job.run_dir().join("report.sha256");
    fs::write(&existing, b"pre-existing\n").unwrap();
    let ran = finish_job(job, false);
    assert_eq!(fs::read(&existing).unwrap(), b"pre-existing\n");
    assert_eq!(ran.outcome.record.output.seal, unsealed(SealStatus::Failed));
    let mut goldens = Goldens::default();
    check_run(&mut goldens, "seal_failed", &lab, &ran, false, false);
    goldens.finish();
}

// ---- refusals ----

#[derive(Serialize)]
struct Refusal {
    case: &'static str,
    error: AppError,
    /// Run folders in the case afterwards.
    run_folders: usize,
}

/// `run_start` refusals (lifecycle step 1): the exact `AppError`, and no run folder (so no
/// `run.json`). `password_required` for an encrypted iTunes backup (also with an empty password)
/// and for one whose encryption cannot be read; the argv path check (E7) for an empty input path
/// and for a `\\?\` path.
#[test]
fn z0_start_refusals() {
    let lab = Lab::new();
    let ev = lab.root.path().join("ev");
    let encrypted = ev.join("bk");
    lab.itunes_backup(&encrypted, true);
    // A Manifest.db without Manifest.plist: still a backup, encryption unknown.
    let unknown = ev.join("no-plist");
    fs::create_dir_all(&unknown).unwrap();
    fs::write(unknown.join("Manifest.db"), b"SQLite format 3\0").unwrap();
    let special = if cfg!(windows) {
        r"\\?\C:\evidence"
    } else {
        "//?/C:/evidence"
    };

    let itunes = |dir: &Path, password: Option<&str>| {
        let mut request = lab.request(ToolId::Ileapp, dir, InputType::Itunes);
        request.itunes_password = password.map(str::to_owned);
        request
    };
    let cases: Vec<(&'static str, RunRequest)> = vec![
        (
            "encrypted_backup_without_password",
            itunes(&encrypted, None),
        ),
        (
            "encrypted_backup_with_an_empty_password",
            itunes(&encrypted, Some("")),
        ),
        ("backup_with_unknown_encryption", itunes(&unknown, None)),
        (
            "empty_input_path",
            lab.request(ToolId::Ileapp, Path::new(""), InputType::Fs),
        ),
        (
            "special_prefix_input_path",
            lab.request(ToolId::Ileapp, Path::new(special), InputType::Fs),
        ),
    ];
    let mut refusals = Vec::new();
    for (case, request) in cases {
        let error = runner::start(request, lab.context(ToolId::Ileapp, "success")).unwrap_err();
        refusals.push(Refusal {
            case,
            error,
            run_folders: lab.run_dirs().len(),
        });
    }
    assert!(!lab.case.path.join("runs").exists());
    let mut normalizer = Normalizer::new();
    normalizer.sub(&lab.root.path().to_string_lossy(), "<LAB>");
    let mut goldens = Goldens::default();
    goldens.check("start-refusals.json", &normalizer.json(&pretty(&refusals)));
    goldens.finish();
}

/// A keychain file whose metadata can be read but whose contents cannot (mode 000; E14): the
/// exact `AppError`, and no run folder. Skipped (with a message) when running with privileges
/// that bypass file permissions.
#[cfg(unix)]
#[test]
fn z0_unreadable_keychain() {
    use std::os::unix::fs::PermissionsExt;

    use suitedfir_core::contracts::ErrorCode;

    let lab = Lab::new();
    let keychain = lab.root.path().join("ev").join("keychain.db");
    fs::write(&keychain, b"keychain bytes").unwrap();
    fs::set_permissions(&keychain, fs::Permissions::from_mode(0o000)).unwrap();
    if fs::File::open(&keychain).is_ok() {
        eprintln!("SKIPPED: running with privileges that bypass file permissions (root)");
        fs::set_permissions(&keychain, fs::Permissions::from_mode(0o644)).unwrap();
        return;
    }
    let mut request = lab.fs_request(ToolId::Ileapp);
    request.keychain_path = Some(keychain.to_string_lossy().into_owned());
    let error = runner::start(request, lab.context(ToolId::Ileapp, "success")).unwrap_err();
    fs::set_permissions(&keychain, fs::Permissions::from_mode(0o644)).unwrap();
    assert!(lab.run_dirs().is_empty());
    let absolute = keychain.to_string_lossy().into_owned();
    let detail = error.detail.clone().unwrap_or_default();
    assert!(detail.starts_with(&format!("{absolute}: ")), "{detail}");
    assert_eq!(
        error,
        AppError {
            code: ErrorCode::PermissionDenied,
            message: "The keychain file could not be read".to_owned(),
            detail: Some(format!("{absolute}: Permission denied (os error 13)")),
        }
    );
}
