//! Z0b acquisition goldens: the behavior baseline of the simplification pass (SIMPLIFY.md §3),
//! characterized on main 24af32c with fake-idevice through the stable entry points
//! (`acquire::start` / `run` / `restore_later`, `recover_case`, `discover`, the contract types).
//!
//! - A normalized golden `acquisition.json` (and `backup.sha256`) for every CONTRACTS.md §13.4 row,
//!   plus `will_encrypt_absent`, `enable_unconfirmed` and the `prepare_failed` / `spawn_failed`
//!   short-circuits; the `encryption-restore[-N].json` files of the later restores.
//! - The ordered `lab.calls()` of `success`, `success_encrypt` and `restore_failed`, and the recorded
//!   `commands[i].argv[1..]` against the fake's recorded call.
//! - The `acq_start` and `restore_later` refusals (exact `AppError`, no attempt file, no `off`).
//! - The event order rules of `success_encrypt`.
//! - The fake's tool output, run as the copied tools, against the goldens of its unit tests.
//!
//! **Comparison.** JSON is compared as text, so key order, nulls, messages and argv are exact.
//! Normalization replaces only run-specific values: the acquisition id (`<ACQ_ID>`), the case id
//! (`<CASE_ID>`), timestamps (`<TIMESTAMP>`, only strings in the RFC 3339 `Z` format), the case
//! folder (`<CASE>`), the tools folder (`<TOOLS>`), the fake binary's hash (`<FAKE_SHA256>`), the
//! app version (`<APP_VERSION>`) and the host (fixed by the test). Placeholders stand for values
//! that depend on timing or on the machine, each checked for presence and type: `duration_ms`
//! (`<DURATION_MS>`, an integer; `null` stays), `free_bytes_after` (`<FREE_BYTES>`, an integer;
//! `null` stays) and, in the cancel rows only, `last_progress_percent` (`<LAST_PROGRESS_PERCENT>`,
//! an integer 0-100 or `null`).
//!
//! **Goldens** live in `tests/golden/acq/`. A file under `tests/golden/acq/<os>/` (`windows`,
//! `linux`) replaces the default (macOS) one on that OS. On a mismatch the normalized actual is
//! printed and written to `<CARGO_TARGET_TMPDIR>/z0b-actual/<os>/`.
//!
//! Frozen: later bundles do not edit this file or its goldens (SIMPLIFY.md §2).

mod common;

use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

use serde::Serialize;

use common::{EXE, Lab, UDID};
use suitedfir_core::acquire::{self, AcqContext, AcqControl, AcqOutcome};
use suitedfir_core::case::{self, CreatedCase};
use suitedfir_core::contracts::{
    AcqEvent, AcqPhase, AcqRequest, AcquisitionRecord, AppError, DeviceChangeKind,
    IdeviceToolsManifest, RecordHost, Timestamp, examples, parse_versioned,
};
use suitedfir_core::hashing;
use suitedfir_core::idevice::Idevice;

const PASSWORD: &str = "k7-Examiner-Pw!";
const GOLDEN_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/golden/acq");
const APP_VERSION: &str = env!("CARGO_PKG_VERSION");

// ---- goldens ----

fn os_name() -> &'static str {
    if cfg!(windows) {
        "windows"
    } else if cfg!(target_os = "linux") {
        "linux"
    } else {
        "macos"
    }
}

/// The golden checks of one test: every mismatch is printed (normalized actual) and saved, and
/// the test fails at [`Goldens::finish`].
#[derive(Default)]
struct Goldens {
    mismatches: Vec<String>,
}

impl Goldens {
    fn check(&mut self, name: &str, actual: &str) {
        let os_file = Path::new(GOLDEN_DIR).join(os_name()).join(name);
        let file = if os_file.is_file() {
            os_file
        } else {
            Path::new(GOLDEN_DIR).join(name)
        };
        let expected = fs::read_to_string(&file).ok();
        if expected.as_deref() == Some(actual) {
            return;
        }
        let saved = Path::new(env!("CARGO_TARGET_TMPDIR"))
            .join("z0b-actual")
            .join(os_name())
            .join(name);
        let _ = fs::create_dir_all(saved.parent().unwrap());
        let _ = fs::write(&saved, actual);
        eprintln!(
            "---- z0b golden mismatch: {name} on {} (golden {}{}; actual saved to {}) ----\n\
             {actual}\n---- end of {name} ----",
            os_name(),
            file.display(),
            if expected.is_none() { ", missing" } else { "" },
            saved.display()
        );
        self.mismatches.push(name.to_owned());
    }

    fn finish(self) {
        assert!(
            self.mismatches.is_empty(),
            "golden mismatches on {} (normalized actuals printed above): {:?}",
            os_name(),
            self.mismatches
        );
    }
}

// ---- normalization ----

/// What a placeholder accepts.
#[derive(Clone, Copy)]
enum Kind {
    /// A non-negative integer; `null` is kept as it is.
    Count,
    /// An integer 0-100, or `null`.
    PercentOrNull,
}

impl Kind {
    fn accepts(self, raw: &str) -> bool {
        match self {
            Kind::Count => raw.parse::<u64>().is_ok(),
            Kind::PercentOrNull => raw == "null" || raw.parse::<u8>().is_ok_and(|p| p <= 100),
        }
    }
}

/// Normalizes JSON text (see the module doc): known run-specific strings are replaced by tokens,
/// timestamps by `<TIMESTAMP>`, and the placeholder keys' values by their tokens.
struct Normalizer {
    /// Run-specific strings, JSON-escaped, and their tokens; applied in order.
    subs: Vec<(String, &'static str)>,
    /// Keys whose value is a placeholder: key, token, what the value must be.
    placeholders: Vec<(&'static str, &'static str, Kind)>,
}

/// `text` as it appears inside a JSON string.
fn escaped(text: &str) -> String {
    let quoted = serde_json::to_string(text).unwrap();
    quoted[1..quoted.len() - 1].to_owned()
}

/// `YYYY-MM-DDTHH:MM:SSZ`.
fn is_timestamp(text: &str) -> bool {
    let bytes = text.as_bytes();
    bytes.len() == 20
        && bytes.iter().enumerate().all(|(i, b)| match i {
            4 | 7 => *b == b'-',
            10 => *b == b'T',
            13 | 16 => *b == b':',
            19 => *b == b'Z',
            _ => b.is_ascii_digit(),
        })
}

/// The end (exclusive) of the JSON string starting at `start` (its opening quote).
fn string_end(bytes: &[u8], start: usize) -> usize {
    let mut i = start + 1;
    loop {
        match bytes[i] {
            b'\\' => i += 2,
            b'"' => return i + 1,
            _ => i += 1,
        }
    }
}

impl Normalizer {
    fn new() -> Self {
        Self {
            subs: Vec::new(),
            placeholders: vec![
                ("duration_ms", "<DURATION_MS>", Kind::Count),
                ("free_bytes_after", "<FREE_BYTES>", Kind::Count),
            ],
        }
    }

    /// For the records of `case` made with the fake tools in `tools_dir`.
    fn for_case(case: &CreatedCase, tools_dir: &Path) -> Self {
        let mut normalizer = Self::new();
        normalizer.sub(&case.path.to_string_lossy(), "<CASE>");
        normalizer.sub(&tools_dir.to_string_lossy(), "<TOOLS>");
        normalizer.sub(&case.case.case_id, "<CASE_ID>");
        normalizer.sub(&fake_sha256(), "<FAKE_SHA256>");
        normalizer
    }

    fn sub(&mut self, text: &str, token: &'static str) -> &mut Self {
        self.subs.push((escaped(text), token));
        self
    }

    fn acq(mut self, acq_id: &str) -> Self {
        self.sub(acq_id, "<ACQ_ID>");
        self
    }

    /// The cancel rows: the last overall percent depends on when the cancel landed.
    fn cancel_row(mut self) -> Self {
        self.placeholders.push((
            "last_progress_percent",
            "<LAST_PROGRESS_PERCENT>",
            Kind::PercentOrNull,
        ));
        self
    }

    fn value(&self, path: &[String], raw: &str) -> String {
        let key = path.last().map_or("", String::as_str);
        if let Some((_, token, kind)) = self.placeholders.iter().find(|(k, ..)| *k == key) {
            return match kind {
                Kind::Count if raw == "null" => raw.to_owned(),
                _ if kind.accepts(raw) => format!("\"{token}\""),
                _ => raw.to_owned(),
            };
        }
        if !raw.starts_with('"') {
            return raw.to_owned();
        }
        let parent = path.len().checked_sub(2).map(|i| path[i].as_str());
        if parent == Some("app") && key == "version" && raw == format!("\"{APP_VERSION}\"") {
            return "\"<APP_VERSION>\"".to_owned();
        }
        let mut text = raw.to_owned();
        for (from, to) in &self.subs {
            text = text.replace(from.as_str(), to);
        }
        if is_timestamp(&text[1..text.len() - 1]) {
            return "\"<TIMESTAMP>\"".to_owned();
        }
        text
    }

    /// Normalizes JSON text, keeping everything else (layout, key order) byte for byte.
    fn json(&self, text: &str) -> String {
        let bytes = text.as_bytes();
        let mut out = String::with_capacity(text.len());
        // The key of each open object (`[]` for arrays), and whether a key comes next.
        let mut path: Vec<String> = Vec::new();
        let mut objects: Vec<bool> = Vec::new();
        let mut want_key = false;
        let mut i = 0;
        while i < bytes.len() {
            match bytes[i] {
                b'{' | b'[' => {
                    let object = bytes[i] == b'{';
                    objects.push(object);
                    path.push(if object {
                        String::new()
                    } else {
                        "[]".to_owned()
                    });
                    want_key = object;
                    out.push(char::from(bytes[i]));
                    i += 1;
                }
                b'}' | b']' => {
                    objects.pop();
                    path.pop();
                    want_key = false;
                    out.push(char::from(bytes[i]));
                    i += 1;
                }
                b',' => {
                    want_key = objects.last() == Some(&true);
                    out.push(',');
                    i += 1;
                }
                b'"' => {
                    let end = string_end(bytes, i);
                    let raw = &text[i..end];
                    if want_key {
                        *path.last_mut().unwrap() = serde_json::from_str(raw).unwrap();
                        want_key = false;
                        out.push_str(raw);
                    } else {
                        out.push_str(&self.value(&path, raw));
                    }
                    i = end;
                }
                b':' | b' ' | b'\n' | b'\r' | b'\t' => {
                    out.push(char::from(bytes[i]));
                    i += 1;
                }
                _ => {
                    let end = bytes[i..]
                        .iter()
                        .position(|b| matches!(b, b',' | b'}' | b']') || b.is_ascii_whitespace())
                        .map_or(bytes.len(), |n| i + n);
                    out.push_str(&self.value(&path, &text[i..end]));
                    i = end;
                }
            }
        }
        out
    }
}

/// The hash of the fake-idevice binary (the tools are copies of it).
fn fake_sha256() -> String {
    hashing::sha256_file(Path::new(common::FAKE)).unwrap()
}

fn pretty<T: Serialize>(value: &T) -> String {
    let mut text = serde_json::to_string_pretty(value).unwrap();
    text.push('\n');
    text
}

// ---- acquisitions ----

fn host() -> RecordHost {
    RecordHost {
        os: "testos".to_owned(),
        os_version: "1.0".to_owned(),
        arch: "testarch".to_owned(),
        hostname: "LAB-TEST-01".to_owned(),
    }
}

fn new_case(lab: &Lab) -> CreatedCase {
    case::create(lab.root.path(), &examples::case_fields()).unwrap()
}

fn context(case: &CreatedCase) -> AcqContext {
    AcqContext {
        case_dir: case.path.clone(),
        case: case.case.clone(),
        host: host(),
    }
}

fn request(case: &CreatedCase, password: Option<&str>) -> AcqRequest {
    AcqRequest {
        case_path: case.path.to_string_lossy().into_owned(),
        udid: UDID.to_owned(),
        label: Some("Golden iPhone".to_owned()),
        enable_encryption: password.is_some(),
        encryption_password: password.map(str::to_owned),
        restore_encryption: true,
    }
}

/// Runs an acquisition to the end; `hook` sees every event (and may cancel through the control).
fn acquire_with(
    idevice: &Idevice,
    case: &CreatedCase,
    request: AcqRequest,
    mut hook: impl FnMut(&AcqEvent, &AcqControl),
) -> (AcqOutcome, Vec<AcqEvent>) {
    let job = acquire::start(idevice, request, context(case)).unwrap();
    let control = job.control();
    let mut events = Vec::new();
    let outcome = job.run(&mut |event| {
        hook(&event, &control);
        events.push(event);
    });
    assert_eq!(outcome.write_error, None);
    (outcome, events)
}

/// A new case and an acquisition in it, with the shared fake tools.
fn simple(
    lab: &Lab,
    password: Option<&str>,
    hook: impl FnMut(&AcqEvent, &AcqControl),
) -> (CreatedCase, AcqOutcome, Vec<AcqEvent>) {
    let case = new_case(lab);
    let (outcome, events) = acquire_with(&lab.idevice, &case, request(&case, password), hook);
    (case, outcome, events)
}

fn acq_dir(outcome: &AcqOutcome) -> PathBuf {
    PathBuf::from(&outcome.summary.acq_dir)
}

fn shared_tools_dir() -> &'static Path {
    &common::shared_tools().0
}

/// Checks `<name>.acquisition.json` and, when one was written, `<name>.backup.sha256` (raw).
fn check_acquisition(
    goldens: &mut Goldens,
    name: &str,
    dir: &Path,
    normalizer: &Normalizer,
) -> String {
    let text = fs::read_to_string(dir.join("acquisition.json")).unwrap();
    let normalized = normalizer.json(&text);
    goldens.check(&format!("{name}.acquisition.json"), &normalized);
    if let Ok(manifest) = fs::read_to_string(dir.join(acquire::BACKUP_MANIFEST)) {
        goldens.check(&format!("{name}.backup.sha256"), &manifest);
    }
    normalized
}

/// One scenario row: an acquisition in `scenario` (with encryption when `password` is given),
/// and its golden record.
fn row(name: &str, scenario: &str, password: Option<&str>) {
    let lab = Lab::new(scenario);
    let (case, outcome, _) = simple(&lab, password, |_, _| {});
    let mut goldens = Goldens::default();
    let normalizer = Normalizer::for_case(&case, shared_tools_dir()).acq(&outcome.record.acq_id);
    check_acquisition(&mut goldens, name, &acq_dir(&outcome), &normalizer);
    goldens.finish();
}

/// `lab.calls()` as normalized JSON.
fn calls_text(calls: &[Vec<String>], normalizer: &Normalizer) -> String {
    normalizer.json(&pretty(&calls))
}

/// The fake's recorded `idevicebackup2` calls.
fn backup2_calls(calls: &[Vec<String>]) -> Vec<Vec<String>> {
    calls
        .iter()
        .filter(|call| call[0] == "idevicebackup2")
        .cloned()
        .collect()
}

// ---- CONTRACTS.md §13.4 rows ----

#[test]
fn z0_success() {
    let lab = Lab::new("success");
    let (case, outcome, _) = simple(&lab, None, |_, _| {});
    let mut goldens = Goldens::default();
    let normalizer = Normalizer::for_case(&case, shared_tools_dir()).acq(&outcome.record.acq_id);
    check_acquisition(&mut goldens, "success", &acq_dir(&outcome), &normalizer);
    let calls = lab.calls();
    goldens.check("success.calls.json", &calls_text(&calls, &normalizer));
    // The recorded backup argv is the one the fake received.
    let record = &outcome.record;
    let spawned = backup2_calls(&calls);
    assert_eq!(record.commands.len(), 1);
    assert_eq!(spawned.len(), 1);
    assert_eq!(record.commands[0].argv[1..], spawned[0][1..]);
    goldens.finish();
}

/// The event sequence without its timing: phases, every log line in order, prompts (at their
/// place among the lines) and the final status. Progress and seal-progress events are left out
/// (their number depends on timing); so are log batch boundaries.
fn event_items(events: &[AcqEvent]) -> Vec<String> {
    let mut items = Vec::new();
    for event in events {
        match event {
            AcqEvent::Phase { phase } => items.push(format!("phase {}", token(phase))),
            AcqEvent::Log { lines } => {
                items.extend(lines.iter().map(|line| format!("line {line}")));
            }
            AcqEvent::DevicePrompt { kind, text } => {
                items.push(format!("prompt {} {text}", token(kind)));
            }
            AcqEvent::Progress { .. } | AcqEvent::SealProgress { .. } => {}
            AcqEvent::Finished { status, .. } => items.push(format!("finished {}", token(status))),
        }
    }
    items
}

/// A contract enum's serialized name.
fn token<T: Serialize>(value: &T) -> String {
    serde_json::to_value(value)
        .unwrap()
        .as_str()
        .unwrap()
        .to_owned()
}

#[test]
fn z0_success_encrypt() {
    let lab = Lab::new("success_encrypt");
    let (case, outcome, events) = simple(&lab, Some(PASSWORD), |_, _| {});
    let mut goldens = Goldens::default();
    let normalizer = Normalizer::for_case(&case, shared_tools_dir()).acq(&outcome.record.acq_id);
    check_acquisition(
        &mut goldens,
        "success_encrypt",
        &acq_dir(&outcome),
        &normalizer,
    );
    let calls = lab.calls();
    goldens.check(
        "success_encrypt.calls.json",
        &calls_text(&calls, &normalizer),
    );

    // commands[i].argv[1..] is exactly what the fake received: encryption on, backup, off.
    let record = &outcome.record;
    let spawned = backup2_calls(&calls);
    assert_eq!(record.commands.len(), 3);
    assert_eq!(spawned.len(), 3, "{spawned:?}");
    for (command, call) in record.commands.iter().zip(&spawned) {
        assert_eq!(command.argv[1..], call[1..], "{:?}", command.purpose);
    }

    // The event order rules: every line is delivered before the next phase, prompt or `finished`
    // event (pinned by the golden sequence), and a prompt event comes right before the log batch
    // that starts with its text.
    for (i, event) in events.iter().enumerate() {
        if let AcqEvent::DevicePrompt { text, .. } = event {
            match events.get(i + 1) {
                Some(AcqEvent::Log { lines }) => assert_eq!(lines.first(), Some(text)),
                other => panic!("after the prompt {text:?} came {other:?}"),
            }
        }
    }
    assert!(matches!(events.last(), Some(AcqEvent::Finished { .. })));
    assert_eq!(
        events
            .iter()
            .filter(|e| matches!(e, AcqEvent::Finished { .. }))
            .count(),
        1
    );
    let items = event_items(&events);
    goldens.check(
        "success_encrypt.events.json",
        &normalizer.json(&pretty(&items)),
    );
    goldens.finish();
}

#[test]
fn z0_already_encrypted() {
    row("already_encrypted", "already_encrypted", None);
}

#[test]
fn z0_restore_fail() {
    let lab = Lab::new("restore_fail");
    let (case, outcome, _) = simple(&lab, Some(PASSWORD), |_, _| {});
    let mut goldens = Goldens::default();
    let acq_id = outcome.record.acq_id.clone();
    let dir = acq_dir(&outcome);
    let normalizer = Normalizer::for_case(&case, shared_tools_dir()).acq(&acq_id);
    check_acquisition(&mut goldens, "restore_fail", &dir, &normalizer);
    let calls = lab.calls();
    goldens.check("restore_fail.calls.json", &calls_text(&calls, &normalizer));
    let spawned = backup2_calls(&calls);
    assert_eq!(spawned.len(), 3, "{spawned:?}");
    for (command, call) in outcome.record.commands.iter().zip(&spawned) {
        assert_eq!(command.argv[1..], call[1..], "{:?}", command.purpose);
    }

    // Later restores: the device still refuses (attempt 1), then accepts (attempt 2).
    let record_bytes = fs::read(dir.join("acquisition.json")).unwrap();
    for (scenario, file) in [
        ("restore_fail", "encryption-restore.json"),
        ("success", "encryption-restore-2.json"),
    ] {
        let before = lab.calls().len();
        acquire::restore_later(
            &lab.reopen(scenario),
            &case.path,
            &acq_id,
            PASSWORD.to_owned(),
            &mut |_| {},
        )
        .unwrap();
        let text = fs::read_to_string(dir.join(file)).unwrap();
        goldens.check(&format!("restore_fail.{file}"), &normalizer.json(&text));
        // The recorded argv is the `off` call the fake received.
        let attempt: suitedfir_core::contracts::EncryptionRestoreRecord =
            parse_versioned(text.as_bytes()).unwrap();
        let off = backup2_calls(&lab.calls()[before..]);
        assert_eq!(off.len(), 1, "{off:?}");
        assert_eq!(attempt.argv[1..], off[0][1..]);
    }
    // acquisition.json was not modified by the later restores.
    assert_eq!(
        fs::read(dir.join("acquisition.json")).unwrap(),
        record_bytes
    );
    goldens.finish();
}

#[test]
fn z0_enable_fail() {
    row("enable_fail", "enable_fail", Some(PASSWORD));
}

#[test]
fn z0_enable_unknown() {
    row("enable_unknown", "enable_unknown", Some(PASSWORD));
}

#[test]
fn z0_backup_fail() {
    row("backup_fail", "backup_fail", None);
}

#[test]
fn z0_backup_fail_encrypted() {
    row(
        "backup_fail_encrypted",
        "backup_fail_encrypted",
        Some(PASSWORD),
    );
}

#[test]
fn z0_incomplete() {
    row("incomplete", "incomplete", None);
}

#[test]
fn z0_cancel_on_device() {
    row("cancel_on_device", "cancel_on_device", None);
}

#[test]
fn z0_disconnect() {
    row("disconnect", "disconnect", None);
}

/// `disconnect` with encryption enabled: the restore is not attempted, so encryption is left on.
#[test]
fn z0_disconnect_encrypted() {
    row("disconnect_encrypted", "disconnect", Some(PASSWORD));
}

#[test]
fn z0_sync_lock() {
    row("sync_lock", "sync_lock", None);
}

#[test]
fn z0_info_empty() {
    row("info_empty", "info_empty", None);
}

#[test]
fn z0_will_encrypt_absent() {
    row("will_encrypt_absent", "will_encrypt_absent", Some(PASSWORD));
}

#[test]
fn z0_enable_unconfirmed() {
    row("enable_unconfirmed", "enable_unconfirmed", Some(PASSWORD));
}

/// Waits until `file` exists (at most 20 s).
fn wait_for(file: &Path) {
    let deadline = Instant::now() + Duration::from_secs(20);
    while !file.exists() {
        assert!(
            Instant::now() < deadline,
            "{} never appeared",
            file.display()
        );
        std::thread::sleep(Duration::from_millis(10));
    }
}

/// Cancels once the backup runs and has written its layout (the slow fake writes `backup.pid`
/// right after it), so the partial backup is the same every time.
fn cancel_row(name: &str, scenario: &str) {
    let lab = Lab::new(scenario);
    let pid_file = lab.state.join("backup.pid");
    let mut cancelled = false;
    let (case, outcome, _) = simple(&lab, None, |event, control| {
        if !cancelled
            && let AcqEvent::Log { lines } = event
            && lines.iter().any(|l| l == "Full backup mode.")
        {
            wait_for(&pid_file);
            cancelled = true;
            control.cancel();
        }
    });
    assert!(cancelled);
    let mut goldens = Goldens::default();
    let normalizer = Normalizer::for_case(&case, shared_tools_dir())
        .acq(&outcome.record.acq_id)
        .cancel_row();
    check_acquisition(&mut goldens, name, &acq_dir(&outcome), &normalizer);
    goldens.finish();
}

/// `slow` + cancel: SIGTERM on Unix; on Windows the job is terminated at once.
#[test]
fn z0_slow_cancel() {
    cancel_row("slow_cancel", "slow");
}

/// `ignore_term` + cancel (Unix): SIGKILL after the 30 s grace.
#[cfg(unix)]
#[test]
fn z0_ignore_term_cancel() {
    cancel_row("ignore_term_cancel", "ignore_term");
}

#[test]
fn z0_cancel_during_enable() {
    let lab = Lab::new("cancel_during_enable");
    let (case, outcome, _) = simple(&lab, Some(PASSWORD), |event, control| {
        if let AcqEvent::DevicePrompt { .. } = event
            && control.phase() == AcqPhase::EnablingEncryption
        {
            control.cancel();
        }
    });
    let mut goldens = Goldens::default();
    let normalizer = Normalizer::for_case(&case, shared_tools_dir())
        .acq(&outcome.record.acq_id)
        .cancel_row();
    check_acquisition(
        &mut goldens,
        "cancel_during_enable",
        &acq_dir(&outcome),
        &normalizer,
    );
    goldens.finish();
}

#[test]
fn z0_cancel_during_restore() {
    let lab = Lab::new("cancel_during_restore");
    let (case, outcome, _) = simple(&lab, Some(PASSWORD), |event, control| {
        if matches!(
            event,
            AcqEvent::Phase {
                phase: AcqPhase::RestoringEncryption
            }
        ) {
            control.cancel();
        }
    });
    let mut goldens = Goldens::default();
    let normalizer = Normalizer::for_case(&case, shared_tools_dir())
        .acq(&outcome.record.acq_id)
        .cancel_row();
    check_acquisition(
        &mut goldens,
        "cancel_during_restore",
        &acq_dir(&outcome),
        &normalizer,
    );
    goldens.finish();
}

/// `not_paired`: the device is paired through the app (Trust on the second try), then acquired.
#[test]
fn z0_not_paired_then_paired() {
    let lab = Lab::new("not_paired");
    lab.idevice.pair(UDID, None).unwrap();
    lab.idevice.pair(UDID, None).unwrap();
    row_with_lab(&lab, "not_paired_then_paired");
}

fn row_with_lab(lab: &Lab, name: &str) {
    let (case, outcome, _) = simple(lab, None, |_, _| {});
    let mut goldens = Goldens::default();
    let normalizer = Normalizer::for_case(&case, shared_tools_dir()).acq(&outcome.record.acq_id);
    check_acquisition(&mut goldens, name, &acq_dir(&outcome), &normalizer);
    goldens.finish();
}

// ---- crash after enable (the runner killed in a child process) ----

const CRASH_CHILD_DIR: &str = "SUITEDFIR_Z0B_CRASH_CHILD_DIR";

/// The runner that `z0_crash_after_enable` kills.
#[test]
#[ignore = "runs only as the child process of z0_crash_after_enable"]
fn z0_crash_after_enable_child() {
    let Some(root) = std::env::var_os(CRASH_CHILD_DIR).map(PathBuf::from) else {
        return;
    };
    let tools = root.join("tools");
    let manifest = common::private_tools(&tools);
    let idevice = common::idevice(
        &tools,
        manifest,
        &root.join("cache"),
        vec![
            ("FAKE_IDEVICE_SCENARIO".into(), "crash_after_enable".into()),
            (
                "FAKE_IDEVICE_STATE_DIR".into(),
                root.join("state").into_os_string(),
            ),
        ],
    );
    let case_dir = root.join("case");
    let case = CreatedCase {
        case: case::load(&case_dir).unwrap(),
        path: case_dir,
    };
    let job = acquire::start(&idevice, request(&case, Some(PASSWORD)), context(&case)).unwrap();
    job.run(&mut |_| {});
    panic!("the runner should have been killed");
}

fn running_record(case_dir: &Path) -> Option<AcquisitionRecord> {
    let entry = fs::read_dir(case_dir.join("acquisitions"))
        .ok()?
        .next()?
        .ok()?;
    parse_versioned(&fs::read(entry.path().join("acquisition.json")).ok()?).ok()
}

/// `crash_after_enable`: the runner is killed once the record shows the enable and the backup
/// holding the sync lock (the last rewrite before the backup ends, so the record is the same every
/// time); the next case open recovers it.
#[test]
fn z0_crash_after_enable() {
    let root = tempfile::tempdir().unwrap();
    fs::create_dir_all(root.path().join("state")).unwrap();
    let fields = suitedfir_core::contracts::CaseFields {
        name: "case".to_owned(),
        ..examples::case_fields()
    };
    let case = case::create(root.path(), &fields).unwrap();
    assert_eq!(case.path, root.path().join("case"));
    let mut child = Command::new(std::env::current_exe().unwrap())
        .args(["--exact", "z0_crash_after_enable_child", "--ignored"])
        .env(CRASH_CHILD_DIR, root.path())
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .unwrap();
    let deadline = Instant::now() + Duration::from_secs(120);
    loop {
        if running_record(&case.path).is_some_and(|r| {
            r.encryption.enabled_by_examiner
                && r.device_changes
                    .iter()
                    .any(|c| c.change == DeviceChangeKind::SyncLockTaken)
        }) {
            break;
        }
        assert!(Instant::now() < deadline, "the backup was never recorded");
        assert!(child.try_wait().unwrap().is_none(), "the child ended early");
        std::thread::sleep(Duration::from_millis(20));
    }
    child.kill().unwrap();
    child.wait().unwrap();
    // On Unix the backup tool (in its own session) outlives the runner; stop it. On Windows the
    // job object took it down with the runner.
    #[cfg(unix)]
    {
        let pid_file = root.path().join("state").join("backup.pid");
        wait_for(&pid_file);
        let pid = fs::read_to_string(&pid_file).unwrap();
        let _ = Command::new("kill").args(["-KILL", pid.trim()]).status();
    }
    let before = running_record(&case.path).unwrap();
    let recovered = acquire::recover_case(&case.path, None, Timestamp::now()).unwrap();
    assert_eq!(recovered, [before.acq_id.as_str()]);
    let dir = acquire::discover(&case.path).unwrap().remove(0).dir;
    let mut goldens = Goldens::default();
    let normalizer = Normalizer::for_case(&case, &root.path().join("tools")).acq(&before.acq_id);
    check_acquisition(&mut goldens, "crash_after_enable", &dir, &normalizer);
    goldens.finish();
}

// ---- the prepare_failed and spawn_failed short-circuits ----

/// A lab with its own copies of the tools (a test removes one).
fn private_lab(scenario: &str) -> (tempfile::TempDir, Lab) {
    let tools = tempfile::tempdir().unwrap();
    let manifest: IdeviceToolsManifest = common::private_tools(tools.path());
    let lab = Lab::with_tools(scenario, &[], tools.path(), manifest);
    (tools, lab)
}

/// `idevicebackup2` disappears after `acq_start` checked the tools: the command that needs it
/// cannot start (`spawn_failed`, naming the command's purpose).
fn spawn_failed_row(name: &str, password: Option<&str>) {
    let (tools, lab) = private_lab("success");
    let case = new_case(&lab);
    let job = acquire::start(&lab.idevice, request(&case, password), context(&case)).unwrap();
    fs::remove_file(tools.path().join(format!("idevicebackup2{EXE}"))).unwrap();
    let outcome = job.run(&mut |_| {});
    assert_eq!(outcome.write_error, None);
    let mut goldens = Goldens::default();
    let normalizer = Normalizer::for_case(&case, tools.path()).acq(&outcome.record.acq_id);
    check_acquisition(&mut goldens, name, &acq_dir(&outcome), &normalizer);
    goldens.finish();
}

#[test]
fn z0_spawn_failed_backup() {
    spawn_failed_row("spawn_failed_backup", None);
}

#[test]
fn z0_spawn_failed_enable() {
    spawn_failed_row("spawn_failed_enable", Some(PASSWORD));
}

/// The job's temp dir (`<app_cache>/tmp/<acq_id>`, ARCHITECTURE.md §8) cannot be created: a file
/// has its name (`prepare_failed`).
#[test]
fn z0_prepare_failed() {
    let lab = Lab::new("success");
    let case = new_case(&lab);
    let job = acquire::start(&lab.idevice, request(&case, None), context(&case)).unwrap();
    let blocker = lab.cache.join("tmp").join(job.acq_id());
    fs::write(&blocker, "not a directory").unwrap();
    let outcome = job.run(&mut |_| {});
    assert_eq!(outcome.write_error, None);
    let mut goldens = Goldens::default();
    let normalizer = Normalizer::for_case(&case, shared_tools_dir()).acq(&outcome.record.acq_id);
    check_acquisition(
        &mut goldens,
        "prepare_failed",
        &acq_dir(&outcome),
        &normalizer,
    );
    goldens.finish();
}

// ---- refusals ----

/// The fake device's recorded calls in `state_dir`.
fn calls_in(state_dir: &Path) -> Vec<Vec<String>> {
    fs::read(state_dir.join("state.json"))
        .ok()
        .map(|bytes| {
            let state: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
            serde_json::from_value(state["calls"].clone()).unwrap()
        })
        .unwrap_or_default()
}

fn pairing_attempts_in(state_dir: &Path) -> Vec<String> {
    fs::read(state_dir.join("state.json"))
        .ok()
        .map(|bytes| {
            let state: serde_json::Value = serde_json::from_slice(&bytes).unwrap();
            serde_json::from_value(state["pairing_attempts"].clone()).unwrap()
        })
        .unwrap_or_default()
}

#[derive(Serialize)]
struct StartRefusal {
    scenario: &'static str,
    error: AppError,
    acquisitions_created: usize,
    calls: Vec<Vec<String>>,
    pairing_attempts: Vec<String>,
}

/// `acq_start` for the §13.4 rows without an acquisition: the exact error, nothing created, and
/// what was run on the device (never a pairing).
#[test]
fn z0_start_refusals() {
    let mut refusals = Vec::new();
    for scenario in [
        "not_paired",
        "locked",
        "trust_denied",
        "pairing_failed",
        "usbmuxd_missing",
    ] {
        let lab = Lab::new(scenario);
        let case = new_case(&lab);
        let err = acquire::start(&lab.idevice, request(&case, None), context(&case)).unwrap_err();
        refusals.push(StartRefusal {
            scenario,
            error: err.into(),
            acquisitions_created: fs::read_dir(case.path.join("acquisitions"))
                .map(|entries| entries.count())
                .unwrap_or(0),
            calls: lab.calls(),
            pairing_attempts: lab.pairing_attempts(),
        });
        lab.assert_no_temp_dirs();
    }
    let mut goldens = Goldens::default();
    goldens.check(
        "start-refusals.json",
        &Normalizer::new().json(&pretty(&refusals)),
    );
    goldens.finish();
}

#[derive(Serialize)]
struct LaterRefusal {
    case: &'static str,
    error: AppError,
    /// The calls the refused attempt made on the device.
    new_calls: Vec<Vec<String>>,
    pairing_attempts: Vec<String>,
    /// The `encryption-restore*` files in the acquisition folder afterwards.
    attempt_files: Vec<String>,
}

fn attempt_files(dir: &Path) -> Vec<String> {
    let mut names: Vec<String> = fs::read_dir(dir)
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .filter(|name| name.starts_with("encryption-restore"))
        .collect();
    names.sort();
    names
}

/// An `Idevice` on the shared tools with a fresh fake-device state in `state_dir` (a device the
/// host has no pair record for, in `not_paired`).
fn fresh_device(lab: &Lab, scenario: &str, state_dir: &Path) -> Idevice {
    fs::create_dir_all(state_dir).unwrap();
    let (tools, manifest) = common::shared_tools();
    common::idevice(
        tools,
        manifest.clone(),
        &lab.cache,
        vec![
            ("FAKE_IDEVICE_SCENARIO".into(), scenario.into()),
            ("FAKE_IDEVICE_STATE_DIR".into(), state_dir.into()),
            ("FAKE_IDEVICE_INTERVAL_MS".into(), "5".into()),
        ],
    )
}

/// `restore_later` refusals on every OS: the device gone, not paired, a 3-character password
/// (also with an unpaired device: the password is checked first). Each gives its exact error,
/// writes no attempt file and runs no `encryption off` (nor any pairing).
#[test]
fn z0_restore_later_refusals() {
    let mut refusals = Vec::new();
    let mut refuse = |case_name: &'static str,
                      idevice: &Idevice,
                      state_dir: &Path,
                      case: &CreatedCase,
                      outcome: &AcqOutcome,
                      password: &str| {
        let before = calls_in(state_dir).len();
        let err = acquire::restore_later(
            idevice,
            &case.path,
            &outcome.record.acq_id,
            password.to_owned(),
            &mut |_| {},
        )
        .unwrap_err();
        let new_calls = calls_in(state_dir)[before..].to_vec();
        assert!(
            !new_calls.iter().any(|call| call.iter().any(|a| a == "off")),
            "{case_name}: {new_calls:?}"
        );
        let files = attempt_files(&acq_dir(outcome));
        assert!(files.is_empty(), "{case_name}: {files:?}");
        refusals.push(LaterRefusal {
            case: case_name,
            error: err.into(),
            new_calls,
            pairing_attempts: pairing_attempts_in(state_dir),
            attempt_files: files,
        });
    };

    // The device disconnected during an encrypted backup and is still gone.
    let lab = Lab::new("disconnect");
    let (case, outcome, _) = simple(&lab, Some(PASSWORD), |_, _| {});
    assert_eq!(outcome.summary.warnings, ["encryption_left_enabled"]);
    refuse(
        "device_missing",
        &lab.idevice,
        &lab.state,
        &case,
        &outcome,
        PASSWORD,
    );
    lab.assert_no_temp_dirs();

    // Encryption was left on (restore_fail).
    let lab = Lab::new("restore_fail");
    let (case, outcome, _) = simple(&lab, Some(PASSWORD), |_, _| {});
    // The device has no pair record for this host now.
    let unpaired = lab.root.path().join("state-unpaired");
    refuse(
        "not_paired",
        &fresh_device(&lab, "not_paired", &unpaired),
        &unpaired,
        &case,
        &outcome,
        PASSWORD,
    );
    refuse(
        "password_3_chars",
        &lab.reopen("success"),
        &lab.state,
        &case,
        &outcome,
        "pw!",
    );
    let unpaired_short = lab.root.path().join("state-unpaired-short");
    refuse(
        "password_3_chars_not_paired",
        &fresh_device(&lab, "not_paired", &unpaired_short),
        &unpaired_short,
        &case,
        &outcome,
        "pw!",
    );
    lab.assert_no_temp_dirs();

    let mut goldens = Goldens::default();
    let normalizer = Normalizer::for_case(&case, shared_tools_dir());
    goldens.check(
        "restore-later-refusals.json",
        &normalizer.json(&pretty(&refusals)),
    );
    goldens.finish();
}

// ---- the fake's tool output ----

/// The copied tools print what the fake's unit-test goldens (`fake/*.xml`) pin.
#[test]
fn z0_fake_tool_output() {
    let tools = shared_tools_dir();
    let udid_args = |rest: &[&'static str]| -> Vec<&'static str> {
        let mut args = vec!["-u", UDID];
        args.extend_from_slice(rest);
        args
    };
    let backup_domain = ["-q", "com.apple.mobile.backup", "-x"];
    let will_encrypt = ["-q", "com.apple.mobile.backup", "-k", "WillEncrypt", "-x"];
    let mut goldens = Goldens::default();
    for (golden, scenario, args) in [
        ("ideviceinfo-x.xml", "success", udid_args(&["-x"])),
        ("ideviceinfo-s-x.xml", "success", udid_args(&["-s", "-x"])),
        (
            "ideviceinfo-q-backup.xml",
            "success",
            udid_args(&backup_domain),
        ),
        (
            "ideviceinfo-q-backup-encrypted.xml",
            "already_encrypted",
            udid_args(&backup_domain),
        ),
        (
            "ideviceinfo-q-backup-without-willencrypt.xml",
            "will_encrypt_absent",
            udid_args(&backup_domain),
        ),
        (
            "ideviceinfo-k-willencrypt.xml",
            "success",
            udid_args(&will_encrypt),
        ),
        (
            "ideviceinfo-k-willencrypt-absent.xml",
            "will_encrypt_absent",
            udid_args(&will_encrypt),
        ),
        (
            "ideviceinfo-q-disk-usage.xml",
            "success",
            udid_args(&["-q", "com.apple.disk_usage", "-x"]),
        ),
    ] {
        let output = Command::new(tools.join(format!("ideviceinfo{EXE}")))
            .args(&args)
            .env("FAKE_IDEVICE_SCENARIO", scenario)
            .env_remove("FAKE_IDEVICE_STATE_DIR")
            .env_remove("FAKE_IDEVICE_DATA_USED")
            .output()
            .unwrap();
        assert_eq!(output.status.code(), Some(0), "{golden}: {output:?}");
        assert!(output.stderr.is_empty(), "{golden}: {output:?}");
        goldens.check(
            &format!("fake/{golden}"),
            &String::from_utf8(output.stdout).unwrap(),
        );
    }
    goldens.finish();
}
