// @ts-check
// Generated by `cargo xtask contracts` from crates/core/src/contracts/examples.rs; do not edit.
// The fixtures of ui/types.d.ts types as an ES module (the *.json files are the same data).
// Enums are exported as { value: true } records, so tsc checks them against the unions exactly.

/** @type {import("../../../ui/types").Settings} */
export const Settings = {
  "schema_version": 1,
  "cases_root": "/Users/examiner/Documents/suiteDFIR Cases",
  "recent_cases": [
    "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar"
  ],
  "defaults": {
    "examiner": "J. Doe",
    "agency": "County Forensics Lab",
    "timezone": "UTC"
  },
  "tools_dir": null
};

/** @type {import("../../../ui/types").CaseFile} */
export const CaseFile = {
  "schema_version": 1,
  "case_id": "5b0c2f4e9a7d4b1f8c3e6a2d1f0b9e7c",
  "name": "Operation Nightjar",
  "case_number": "2026-0142",
  "examiner": "J. Doe",
  "agency": "County Forensics Lab",
  "description": "",
  "default_timezone": "America/Chicago",
  "created_at": "2026-09-24T18:10:00Z",
  "updated_at": "2026-09-24T18:10:00Z",
  "created_by_app_version": "0.2.0"
};

/** @type {import("../../../ui/types").RunRecord} */
export const RunRecord = {
  "schema_version": 1,
  "run_id": "20260924-183005Z-ileapp-3f9a1c",
  "label": "iPhone 12 Finder backup",
  "status": "completed_with_errors",
  "status_reasons": [
    {
      "code": "modules_errored",
      "message": "2 modules reported Error: foo, bar"
    }
  ],
  "warnings": [
    {
      "code": "stderr_traceback",
      "message": "stderr contains a Python traceback (see leapp.stderr.log)"
    }
  ],
  "created_at": "2026-09-24T18:30:05Z",
  "started_at": "2026-09-24T18:30:06Z",
  "ended_at": "2026-09-24T18:52:41Z",
  "recovered_at": null,
  "duration_ms": 1356000,
  "app": {
    "name": "suiteDFIR",
    "version": "0.2.0"
  },
  "host": {
    "os": "macos",
    "os_version": "15.6",
    "arch": "aarch64",
    "hostname": "LAB-MAC-01"
  },
  "case_snapshot": {
    "case_id": "5b0c2f4e9a7d4b1f8c3e6a2d1f0b9e7c",
    "name": "Operation Nightjar",
    "case_number": "2026-0142",
    "examiner": "J. Doe",
    "agency": "County Forensics Lab"
  },
  "tool": {
    "id": "ileapp",
    "version": "v2026.4.2",
    "platform": "macos-aarch64",
    "asset_name": "ileapp-v2026.4.2-macOS_Apple_Silicon.zip",
    "asset_sha256": "d99f2d05dbde20ee997de477c38443d4f019d60326a8c6b9456058c6cf590386",
    "entry_sha256": "71dda0d3326d5f5f22a081a296fa2b09292f071680084ab5154d7429e73c2e06",
    "entry_verified_against": "manifest",
    "install_source": "download"
  },
  "input": {
    "path": "/Volumes/Evidence/00008101-000A1B2C3D4E",
    "kind": "directory",
    "type": "itunes",
    "type_detected": "itunes",
    "size_bytes": null,
    "itunes_encrypted": true,
    "acquisition_id": null,
    "hash": {
      "algorithm": "sha256",
      "status": "not_applicable",
      "value": null,
      "started_at": null,
      "completed_at": null
    }
  },
  "options": {
    "timezone": "America/Chicago",
    "timezone_supported": true,
    "password_supplied": true,
    "keychain_path": null,
    "keychain_sha256": null
  },
  "modules": {
    "mode": "custom",
    "profile_name": null,
    "requested": [
      "callHistory",
      "sms"
    ],
    "resolved": [
      "callHistory",
      "sms"
    ],
    "unknown": [],
    "always_run": [
      "itunes_backup_info",
      "itunes_backup_installed_applications"
    ],
    "available_count": 1176
  },
  "command": {
    "argv": [
      "/Users/examiner/Library/Application Support/com.suitedfir.desktop/leapp/ileapp/v2026.4.2/bin/ileapp",
      "-t",
      "itunes",
      "-i",
      "/Volumes/Evidence/00008101-000A1B2C3D4E",
      "-o",
      "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/runs/20260924-183005Z-ileapp-3f9a1c",
      "--custom_output_folder",
      "report",
      "-d",
      "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/runs/20260924-183005Z-ileapp-3f9a1c/case.lcasedata",
      "-m",
      "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/runs/20260924-183005Z-ileapp-3f9a1c/profile.ilprofile",
      "-tz",
      "America/Chicago",
      "--itunes_password",
      "<redacted>"
    ],
    "cwd": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/runs/20260924-183005Z-ileapp-3f9a1c"
  },
  "process": {
    "exit_code": 0,
    "signal": null,
    "exited_at": "2026-09-24T18:51:10Z",
    "cancel_requested": false,
    "escalated_to_kill": false
  },
  "leapp_result": {
    "lava_data_found": true,
    "processing_status": "Complete",
    "leapp_version_reported": "2026.4.2",
    "index_html_found": true,
    "module_counts": {
      "complete": 120,
      "error": 2,
      "no_files_found": 1054,
      "other": 0
    },
    "error_modules": [
      "foo",
      "bar"
    ]
  },
  "output": {
    "report_dir": "report",
    "seal": {
      "status": "sealed",
      "manifest": "report.sha256",
      "manifest_sha256": "16c6428a0dd24eeb087bcb072aee9a16d37d29aa661f6b16cddbec25d4f2c9aa",
      "file_count": 5321,
      "total_bytes": 123456789
    }
  },
  "logs": {
    "stdout": "leapp.stdout.log",
    "stderr": "leapp.stderr.log",
    "screen_output": "report/_HTML/_Script_Logs/Screen_Output.html"
  }
};

/** @type {import("../../../ui/types").RunRecord} */
export const RunRecordInitial = {
  "schema_version": 1,
  "run_id": "20260924-183005Z-ileapp-3f9a1c",
  "label": "iPhone 12 Finder backup",
  "status": "running",
  "status_reasons": [],
  "warnings": [],
  "created_at": "2026-09-24T18:30:05Z",
  "started_at": null,
  "ended_at": null,
  "recovered_at": null,
  "duration_ms": null,
  "app": {
    "name": "suiteDFIR",
    "version": "0.2.0"
  },
  "host": {
    "os": "macos",
    "os_version": "15.6",
    "arch": "aarch64",
    "hostname": "LAB-MAC-01"
  },
  "case_snapshot": {
    "case_id": "5b0c2f4e9a7d4b1f8c3e6a2d1f0b9e7c",
    "name": "Operation Nightjar",
    "case_number": "2026-0142",
    "examiner": "J. Doe",
    "agency": "County Forensics Lab"
  },
  "tool": {
    "id": "ileapp",
    "version": "v2026.4.2",
    "platform": "macos-aarch64",
    "asset_name": "ileapp-v2026.4.2-macOS_Apple_Silicon.zip",
    "asset_sha256": "d99f2d05dbde20ee997de477c38443d4f019d60326a8c6b9456058c6cf590386",
    "entry_sha256": "71dda0d3326d5f5f22a081a296fa2b09292f071680084ab5154d7429e73c2e06",
    "entry_verified_against": "manifest",
    "install_source": "download"
  },
  "input": {
    "path": "/Volumes/Evidence/00008101-000A1B2C3D4E",
    "kind": "directory",
    "type": "itunes",
    "type_detected": "itunes",
    "size_bytes": null,
    "itunes_encrypted": true,
    "acquisition_id": null,
    "hash": {
      "algorithm": "sha256",
      "status": "not_applicable",
      "value": null,
      "started_at": null,
      "completed_at": null
    }
  },
  "options": {
    "timezone": "America/Chicago",
    "timezone_supported": true,
    "password_supplied": true,
    "keychain_path": null,
    "keychain_sha256": null
  },
  "modules": {
    "mode": "custom",
    "profile_name": null,
    "requested": [
      "callHistory",
      "sms"
    ],
    "resolved": [
      "callHistory",
      "sms"
    ],
    "unknown": [],
    "always_run": [
      "itunes_backup_info",
      "itunes_backup_installed_applications"
    ],
    "available_count": 1176
  },
  "command": {
    "argv": [
      "/Users/examiner/Library/Application Support/com.suitedfir.desktop/leapp/ileapp/v2026.4.2/bin/ileapp",
      "-t",
      "itunes",
      "-i",
      "/Volumes/Evidence/00008101-000A1B2C3D4E",
      "-o",
      "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/runs/20260924-183005Z-ileapp-3f9a1c",
      "--custom_output_folder",
      "report",
      "-d",
      "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/runs/20260924-183005Z-ileapp-3f9a1c/case.lcasedata",
      "-m",
      "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/runs/20260924-183005Z-ileapp-3f9a1c/profile.ilprofile",
      "-tz",
      "America/Chicago",
      "--itunes_password",
      "<redacted>"
    ],
    "cwd": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/runs/20260924-183005Z-ileapp-3f9a1c"
  },
  "process": null,
  "leapp_result": null,
  "output": {
    "report_dir": "report",
    "seal": {
      "status": "pending",
      "manifest": null,
      "manifest_sha256": null,
      "file_count": null,
      "total_bytes": null
    }
  },
  "logs": {
    "stdout": "leapp.stdout.log",
    "stderr": "leapp.stderr.log",
    "screen_output": "report/_HTML/_Script_Logs/Screen_Output.html"
  }
};

/** @type {import("../../../ui/types").AcquisitionRecord} */
export const AcquisitionRecord = {
  "schema_version": 1,
  "acq_id": "20260924-171200Z-ios-9c01de",
  "label": "Suspect iPhone 12",
  "status": "succeeded",
  "status_reasons": [],
  "warnings": [],
  "created_at": "2026-09-24T17:12:00Z",
  "started_at": "2026-09-24T17:12:04Z",
  "ended_at": "2026-09-24T17:48:51Z",
  "recovered_at": null,
  "duration_ms": 2211000,
  "app": {
    "name": "suiteDFIR",
    "version": "0.2.0"
  },
  "host": {
    "os": "macos",
    "os_version": "15.6",
    "arch": "aarch64",
    "hostname": "LAB-MAC-01"
  },
  "case_snapshot": {
    "case_id": "5b0c2f4e9a7d4b1f8c3e6a2d1f0b9e7c",
    "name": "Operation Nightjar",
    "case_number": "2026-0142",
    "examiner": "J. Doe",
    "agency": "County Forensics Lab"
  },
  "device": {
    "udid": "00008101-000A1B2C3D4E001E",
    "serial_number": "F2LXXXXXXX",
    "device_name": "Alex's iPhone",
    "product_type": "iPhone13,2",
    "product_version": "18.6",
    "build_version": "22G86",
    "captured_at": "2026-09-24T17:12:01Z",
    "info_file": "device-info.plist",
    "info_file_sha256": "30850597bc288cc05c5b0d037d179d2ca8bc29586b578b82c1f11116fe4a8bc1"
  },
  "pairing": {
    "paired_before": false,
    "paired_by_app_at": "2026-09-24T17:10:40Z",
    "host_id": "5E1B7C2A-9D4F-4E8B-A3C6-1F0D2B7E9A48",
    "system_buid": "0C6F3A9E-2B7D-4C1E-8F5A-6D9B3E0A7C21"
  },
  "device_changes": [
    {
      "at": "2026-09-24T17:10:40Z",
      "change": "pair_record_created",
      "detail": "Trusted this computer via idevicepair pair"
    },
    {
      "at": "2026-09-24T17:12:05Z",
      "change": "backup_encryption_enabled",
      "detail": "WillEncrypt false → true"
    },
    {
      "at": "2026-09-24T17:12:09Z",
      "change": "sync_lock_taken",
      "detail": "idevicebackup2 holds /com.apple.itunes.lock_sync during backup"
    },
    {
      "at": "2026-09-24T17:48:40Z",
      "change": "backup_encryption_disabled",
      "detail": "WillEncrypt true → false"
    }
  ],
  "tools": {
    "version": "1.4.0",
    "source": "bundled",
    "binaries": {
      "idevice_id": {
        "path": "/Applications/suiteDFIR.app/Contents/MacOS/idevice_id",
        "sha256": "79d2ee9abcf31cbcffa307540f3b544422d3bcaa5f84512b0324ea73058a6070",
        "verified_against": "code_signature"
      },
      "ideviceinfo": {
        "path": "/Applications/suiteDFIR.app/Contents/MacOS/ideviceinfo",
        "sha256": "a6b284f9e83befa4d8338cde3bb7890420b196fc8e22d2fbce6b88af18ae2667",
        "verified_against": "code_signature"
      },
      "idevicepair": {
        "path": "/Applications/suiteDFIR.app/Contents/MacOS/idevicepair",
        "sha256": "3ef6a531ea00523d2049dec59bbf8813249d061e2859753dd0351157794e2e82",
        "verified_against": "code_signature"
      },
      "idevicebackup2": {
        "path": "/Applications/suiteDFIR.app/Contents/MacOS/idevicebackup2",
        "sha256": "945993e323408b74219c4efc24a2c24bcf76d0dc352ec26e537177c1cd09a2d2",
        "verified_against": "code_signature"
      }
    }
  },
  "encryption": {
    "will_encrypt_before": false,
    "enable_requested": true,
    "enabled_by_examiner": true,
    "will_encrypt_after_enable": true,
    "restore_requested": true,
    "restored_after": "restored",
    "will_encrypt_after_restore": false,
    "password_supplied": true,
    "password_channel": "env"
  },
  "commands": [
    {
      "purpose": "enable_encryption",
      "argv": [
        "/Applications/suiteDFIR.app/Contents/MacOS/idevicebackup2",
        "-u",
        "00008101-000A1B2C3D4E001E",
        "encryption",
        "on"
      ],
      "exit_code": 0,
      "started_at": "2026-09-24T17:12:04Z",
      "exited_at": "2026-09-24T17:12:05Z"
    },
    {
      "purpose": "backup",
      "argv": [
        "/Applications/suiteDFIR.app/Contents/MacOS/idevicebackup2",
        "-u",
        "00008101-000A1B2C3D4E001E",
        "backup",
        "--full",
        "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/acquisitions/20260924-171200Z-ios-9c01de/backup"
      ],
      "exit_code": 0,
      "started_at": "2026-09-24T17:12:09Z",
      "exited_at": "2026-09-24T17:48:30Z"
    },
    {
      "purpose": "restore_encryption",
      "argv": [
        "/Applications/suiteDFIR.app/Contents/MacOS/idevicebackup2",
        "-u",
        "00008101-000A1B2C3D4E001E",
        "encryption",
        "off"
      ],
      "exit_code": 0,
      "started_at": "2026-09-24T17:48:31Z",
      "exited_at": "2026-09-24T17:48:40Z"
    }
  ],
  "process": {
    "exit_code": 0,
    "signal": null,
    "cancel_requested": false,
    "escalated_to_kill": false
  },
  "backup_result": {
    "final_message": "Backup Successful.",
    "udid_dir": "backup/00008101-000A1B2C3D4E001E",
    "manifest_found": "Manifest.db",
    "info_plist_found": true,
    "status_plist_found": true,
    "snapshot_state": "finished",
    "last_progress_percent": 100,
    "device_file_errors": 0,
    "free_bytes_after": 81234567890
  },
  "output": {
    "backup_dir": "backup",
    "seal": {
      "status": "sealed",
      "manifest": "backup.sha256",
      "manifest_sha256": "3c77d9ed56c5af819196f7b12d7830783bd93468712a9a3cb505e77f2061212f",
      "file_count": 48210,
      "total_bytes": 61203455110
    }
  },
  "logs": {
    "stdout": "idevicebackup2.stdout.log",
    "stderr": "idevicebackup2.stderr.log"
  }
};

/** @type {import("../../../ui/types").AppError} */
export const AppError = {
  "code": "tool_not_installed",
  "message": "iLEAPP v2026.4.2 is not installed.",
  "detail": "/Users/examiner/Library/Application Support/com.suitedfir.desktop/leapp/ileapp/v2026.4.2/install.json does not exist"
};

/** @type {import("../../../ui/types").Reason} */
export const Reason = {
  "code": "modules_errored",
  "message": "2 modules reported Error: foo, bar"
};

/** @type {import("../../../ui/types").ToolStatus} */
export const ToolStatus = {
  "tool": "ileapp",
  "display_name": "iLEAPP",
  "pinned_version": "v2026.4.2",
  "state": "verified",
  "installed_version": "v2026.4.2",
  "install_source": "download",
  "module_count": 1176,
  "install_dir": "/Users/examiner/Library/Application Support/com.suitedfir.desktop/leapp/ileapp/v2026.4.2",
  "problem": null
};

/** @type {import("../../../ui/types").ToolModules} */
export const ToolModules = {
  "tool": "ileapp",
  "version": "v2026.4.2",
  "always_run": {
    "default": [
      "last_build"
    ],
    "itunes": [
      "itunes_backup_info",
      "itunes_backup_installed_applications"
    ]
  },
  "timezones": [
    "Africa/Abidjan",
    "America/Chicago",
    "UTC"
  ],
  "modules": [
    {
      "name": "callHistory",
      "module_name": "callHistory",
      "category": "Call History",
      "display_name": "Call History",
      "description": null
    },
    {
      "name": "sms",
      "module_name": "sms",
      "category": "SMS & iMessage",
      "display_name": "SMS & iMessage",
      "description": "Messages from sms.db"
    }
  ]
};

/** @type {import("../../../ui/types").ModuleInfo} */
export const ModuleInfo = {
  "name": "callHistory",
  "module_name": "callHistory",
  "category": "Call History",
  "display_name": "Call History",
  "description": null
};

/** @type {import("../../../ui/types").CaseSummary} */
export const CaseSummary = {
  "path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
  "exists": true,
  "case": {
    "schema_version": 1,
    "case_id": "5b0c2f4e9a7d4b1f8c3e6a2d1f0b9e7c",
    "name": "Operation Nightjar",
    "case_number": "2026-0142",
    "examiner": "J. Doe",
    "agency": "County Forensics Lab",
    "description": "",
    "default_timezone": "America/Chicago",
    "created_at": "2026-09-24T18:10:00Z",
    "updated_at": "2026-09-24T18:10:00Z",
    "created_by_app_version": "0.2.0"
  },
  "run_count": 1,
  "last_run_at": "2026-09-24T18:30:05Z"
};

/** @type {import("../../../ui/types").CaseDetail} */
export const CaseDetail = {
  "path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
  "case": {
    "schema_version": 1,
    "case_id": "5b0c2f4e9a7d4b1f8c3e6a2d1f0b9e7c",
    "name": "Operation Nightjar",
    "case_number": "2026-0142",
    "examiner": "J. Doe",
    "agency": "County Forensics Lab",
    "description": "",
    "default_timezone": "America/Chicago",
    "created_at": "2026-09-24T18:10:00Z",
    "updated_at": "2026-09-24T18:10:00Z",
    "created_by_app_version": "0.2.0"
  },
  "runs": [
    {
      "run_id": "20260924-183005Z-ileapp-3f9a1c",
      "run_dir": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/runs/20260924-183005Z-ileapp-3f9a1c",
      "label": "iPhone 12 Finder backup",
      "status": "completed_with_errors",
      "tool": "ileapp",
      "tool_version": "v2026.4.2",
      "input_path": "/Volumes/Evidence/00008101-000A1B2C3D4E",
      "input_type": "itunes",
      "created_at": "2026-09-24T18:30:05Z",
      "started_at": "2026-09-24T18:30:06Z",
      "ended_at": "2026-09-24T18:52:41Z",
      "duration_ms": 1356000,
      "report_available": true
    }
  ],
  "acquisitions": [
    {
      "acq_id": "20260924-171200Z-ios-9c01de",
      "acq_dir": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/acquisitions/20260924-171200Z-ios-9c01de",
      "label": "Suspect iPhone 12",
      "status": "succeeded",
      "udid": "00008101-000A1B2C3D4E001E",
      "device_name": "Alex's iPhone",
      "product_version": "18.6",
      "created_at": "2026-09-24T17:12:00Z",
      "started_at": "2026-09-24T17:12:04Z",
      "ended_at": "2026-09-24T17:48:51Z",
      "duration_ms": 2211000,
      "backup_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/acquisitions/20260924-171200Z-ios-9c01de/backup/00008101-000A1B2C3D4E001E",
      "warnings": []
    }
  ],
  "recovered": []
};

/** @type {import("../../../ui/types").RunSummary} */
export const RunSummary = {
  "run_id": "20260924-183005Z-ileapp-3f9a1c",
  "run_dir": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/runs/20260924-183005Z-ileapp-3f9a1c",
  "label": "iPhone 12 Finder backup",
  "status": "completed_with_errors",
  "tool": "ileapp",
  "tool_version": "v2026.4.2",
  "input_path": "/Volumes/Evidence/00008101-000A1B2C3D4E",
  "input_type": "itunes",
  "created_at": "2026-09-24T18:30:05Z",
  "started_at": "2026-09-24T18:30:06Z",
  "ended_at": "2026-09-24T18:52:41Z",
  "duration_ms": 1356000,
  "report_available": true
};

/** @type {import("../../../ui/types").InputInspection} */
export const InputInspection = {
  "path": "/Volumes/Evidence/00008101-000A1B2C3D4E",
  "kind": "directory",
  "size_bytes": null,
  "detected_type": "itunes",
  "allowed_types": [
    "fs",
    "itunes"
  ],
  "is_itunes_backup": true,
  "itunes_encrypted": true,
  "hashable": false,
  "warnings": []
};

/** @type {import("../../../ui/types").ModuleSelection[]} */
export const ModuleSelection = [
  {
    "mode": "all"
  },
  {
    "mode": "profile",
    "profile_name": "Messaging"
  },
  {
    "mode": "custom",
    "modules": [
      "callHistory",
      "sms"
    ]
  }
];

/** @type {import("../../../ui/types").RunRequest} */
export const RunRequest = {
  "case_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
  "tool": "ileapp",
  "input_path": "/Volumes/Evidence/00008101-000A1B2C3D4E",
  "input_type": "itunes",
  "modules": {
    "mode": "custom",
    "modules": [
      "callHistory",
      "sms"
    ]
  },
  "timezone": "America/Chicago",
  "itunes_password": "example-backup-password",
  "keychain_path": null,
  "hash_input": false,
  "label": "iPhone 12 Finder backup"
};

/** @type {import("../../../ui/types").ActiveJob[]} */
export const ActiveJob = [
  {
    "kind": "run",
    "case_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
    "run_id": "20260924-183005Z-ileapp-3f9a1c",
    "tool": "ileapp",
    "created_at": "2026-09-24T18:30:05Z",
    "phase": "running"
  },
  {
    "kind": "acquisition",
    "case_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
    "acq_id": "20260924-171200Z-ios-9c01de",
    "udid": "00008101-000A1B2C3D4E001E",
    "created_at": "2026-09-24T17:12:00Z",
    "phase": "backing_up"
  }
];

/** @type {import("../../../ui/types").ProfileInfo} */
export const ProfileInfo = {
  "tool": "ileapp",
  "name": "Messaging",
  "modules": [
    "callHistory",
    "sms",
    "noSuchModule"
  ],
  "unknown_modules": [
    "noSuchModule"
  ]
};

/** @type {import("../../../ui/types").IosBackup} */
export const IosBackup = {
  "path": "/Users/examiner/Library/Application Support/MobileSync/Backup/00008101-000A1B2C3D4E001E",
  "device_name": "Alex's iPhone",
  "product_type": "iPhone13,2",
  "ios_version": "18.6",
  "last_backup": "2026-09-20T21:04:33Z",
  "encrypted": true,
  "size_bytes": 61203455110
};

/** @type {import("../../../ui/types").AppInfo} */
export const AppInfo = {
  "app_version": "0.2.0",
  "platform": "macos-aarch64",
  "os": "macos",
  "arch": "aarch64",
  "dev_override": false,
  "paths": {
    "app_data": "/Users/examiner/Library/Application Support/com.suitedfir.desktop",
    "app_config": "/Users/examiner/Library/Application Support/com.suitedfir.desktop",
    "app_cache": "/Users/examiner/Library/Caches/com.suitedfir.desktop",
    "app_log": "/Users/examiner/Library/Logs/com.suitedfir.desktop",
    "tools_dir": "/Users/examiner/Library/Application Support/com.suitedfir.desktop/leapp"
  }
};

/** @type {import("../../../ui/types").SettingsUpdateRequest} */
export const SettingsUpdateRequest = {
  "cases_root": "/Volumes/Cases/suiteDFIR Cases",
  "tools_dir": null
};

/** @type {import("../../../ui/types").ToolRequest} */
export const ToolRequest = {
  "tool": "ileapp"
};

/** @type {import("../../../ui/types").ToolImportRequest} */
export const ToolImportRequest = {
  "tool": "ileapp",
  "archive_path": "/Users/examiner/Downloads/ileapp-v2026.4.2-macOS_Apple_Silicon.zip"
};

/** @type {import("../../../ui/types").CaseCreateRequest} */
export const CaseCreateRequest = {
  "name": "Operation Nightjar",
  "case_number": "2026-0142",
  "examiner": "J. Doe",
  "agency": "County Forensics Lab",
  "description": "Seized handset, item 3",
  "default_timezone": "America/Chicago",
  "parent_dir": null
};

/** @type {import("../../../ui/types").PathRequest} */
export const PathRequest = {
  "path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar"
};

/** @type {import("../../../ui/types").CaseUpdateRequest} */
export const CaseUpdateRequest = {
  "path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
  "fields": {
    "name": "Operation Nightjar",
    "case_number": "2026-0142",
    "examiner": "J. Doe",
    "agency": "County Forensics Lab",
    "description": "Seized handset, item 3",
    "default_timezone": "America/Chicago"
  }
};

/** @type {import("../../../ui/types").CaseFields} */
export const CaseFields = {
  "name": "Operation Nightjar",
  "case_number": "2026-0142",
  "examiner": "J. Doe",
  "agency": "County Forensics Lab",
  "description": "Seized handset, item 3",
  "default_timezone": "America/Chicago"
};

/** @type {import("../../../ui/types").RunRef} */
export const RunRef = {
  "case_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
  "run_id": "20260924-183005Z-ileapp-3f9a1c"
};

/** @type {import("../../../ui/types").InputInspectRequest} */
export const InputInspectRequest = {
  "tool": "ileapp",
  "path": "/Volumes/Evidence/00008101-000A1B2C3D4E",
  "case_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar"
};

/** @type {import("../../../ui/types").ProfileSaveRequest} */
export const ProfileSaveRequest = {
  "tool": "ileapp",
  "name": "Messaging",
  "modules": [
    "callHistory",
    "sms"
  ]
};

/** @type {import("../../../ui/types").ProfileRef} */
export const ProfileRef = {
  "tool": "ileapp",
  "name": "Messaging"
};

/** @type {import("../../../ui/types").ProfileImportRequest} */
export const ProfileImportRequest = {
  "tool": "ileapp",
  "path": "/Users/examiner/Downloads/Messaging.ilprofile",
  "name": null,
  "overwrite": false
};

/** @type {import("../../../ui/types").ProfileExportRequest} */
export const ProfileExportRequest = {
  "tool": "ileapp",
  "name": "Messaging",
  "dest_path": "/Users/examiner/Desktop/Messaging.ilprofile"
};

/** @type {import("../../../ui/types").RunStarted} */
export const RunStarted = {
  "run_id": "20260924-183005Z-ileapp-3f9a1c",
  "run_dir": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/runs/20260924-183005Z-ileapp-3f9a1c"
};

/** @type {import("../../../ui/types").RunCancelRequest} */
export const RunCancelRequest = {
  "run_id": "20260924-183005Z-ileapp-3f9a1c"
};

/** @type {import("../../../ui/types").JobAttachRequest} */
export const JobAttachRequest = {
  "kind": "run",
  "id": "20260924-183005Z-ileapp-3f9a1c"
};

/** @type {import("../../../ui/types").JobBacklog} */
export const JobBacklog = {
  "backlog": [
    "Processing iTunes backup",
    "callHistory [Call History] artifact executed"
  ]
};

/** @type {import("../../../ui/types").OpenTextFileRequest} */
export const OpenTextFileRequest = {
  "case_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
  "run_id": "20260924-183005Z-ileapp-3f9a1c",
  "which": "stderr"
};

/** @type {import("../../../ui/types").TempCleanupResult} */
export const TempCleanupResult = {
  "freed_bytes": 132120576
};

/** @type {import("../../../ui/types").RunEvent[]} */
export const RunEvent = [
  {
    "type": "phase",
    "phase": "running"
  },
  {
    "type": "log",
    "lines": [
      "Processing iTunes backup",
      "callHistory [Call History] artifact executed"
    ]
  },
  {
    "type": "stdio_tail",
    "stream": "stderr",
    "lines": [
      "Traceback (most recent call last):",
      "  File \"foo.py\""
    ]
  },
  {
    "type": "hash_progress",
    "bytes_done": 1048576,
    "bytes_total": 67108864
  },
  {
    "type": "seal_progress",
    "files_done": 2000,
    "files_total": 5321
  },
  {
    "type": "finished",
    "status": "completed_with_errors",
    "reasons": [
      {
        "code": "modules_errored",
        "message": "2 modules reported Error: foo, bar"
      }
    ],
    "warnings": [
      {
        "code": "stderr_traceback",
        "message": "stderr contains a Python traceback (see leapp.stderr.log)"
      }
    ],
    "summary": {
      "run_id": "20260924-183005Z-ileapp-3f9a1c",
      "run_dir": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/runs/20260924-183005Z-ileapp-3f9a1c",
      "label": "iPhone 12 Finder backup",
      "status": "completed_with_errors",
      "tool": "ileapp",
      "tool_version": "v2026.4.2",
      "input_path": "/Volumes/Evidence/00008101-000A1B2C3D4E",
      "input_type": "itunes",
      "created_at": "2026-09-24T18:30:05Z",
      "started_at": "2026-09-24T18:30:06Z",
      "ended_at": "2026-09-24T18:52:41Z",
      "duration_ms": 1356000,
      "report_available": true
    }
  }
];

/** @type {import("../../../ui/types").InstallEvent[]} */
export const InstallEvent = [
  {
    "type": "stage",
    "stage": "downloading"
  },
  {
    "type": "download_progress",
    "bytes_done": 10485760,
    "bytes_total": 55085487
  },
  {
    "type": "message",
    "text": "Verifying the asset hash"
  }
];

/** @type {import("../../../ui/types").DeviceSummary} */
export const DeviceSummary = {
  "udid": "00008101-000A1B2C3D4E001E",
  "device_name": "Alex's iPhone",
  "product_type": "iPhone13,2",
  "product_version": "18.6",
  "serial_number": "F2LXXXXXXX",
  "pair_state": "paired",
  "busy": false,
  "will_encrypt": false,
  "data_used_bytes": 61203455110,
  "data_capacity_bytes": 118111600640,
  "message": null
};

/** @type {import("../../../ui/types").DevicesResult} */
export const DevicesResult = {
  "tools": {
    "source": "bundled",
    "version": "1.4.0",
    "state": "ok",
    "guidance": null
  },
  "devices": [
    {
      "udid": "00008101-000A1B2C3D4E001E",
      "device_name": "Alex's iPhone",
      "product_type": "iPhone13,2",
      "product_version": "18.6",
      "serial_number": "F2LXXXXXXX",
      "pair_state": "paired",
      "busy": false,
      "will_encrypt": false,
      "data_used_bytes": 61203455110,
      "data_capacity_bytes": 118111600640,
      "message": null
    }
  ]
};

/** @type {import("../../../ui/types").DevicePairRequest} */
export const DevicePairRequest = {
  "udid": "00008101-000A1B2C3D4E001E"
};

/** @type {import("../../../ui/types").AcqPreflightRequest} */
export const AcqPreflightRequest = {
  "case_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
  "udid": "00008101-000A1B2C3D4E001E"
};

/** @type {import("../../../ui/types").AcqPreflight} */
export const AcqPreflight = {
  "free_bytes": 412316860416,
  "required_bytes": 61203455110,
  "level": "ok"
};

/** @type {import("../../../ui/types").AcqRequest} */
export const AcqRequest = {
  "case_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
  "udid": "00008101-000A1B2C3D4E001E",
  "label": "Suspect iPhone 12",
  "enable_encryption": true,
  "encryption_password": "example-backup-password",
  "restore_encryption": true
};

/** @type {import("../../../ui/types").AcqStarted} */
export const AcqStarted = {
  "acq_id": "20260924-171200Z-ios-9c01de",
  "acq_dir": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/acquisitions/20260924-171200Z-ios-9c01de"
};

/** @type {import("../../../ui/types").AcqCancelRequest} */
export const AcqCancelRequest = {
  "acq_id": "20260924-171200Z-ios-9c01de"
};

/** @type {import("../../../ui/types").AcqRef} */
export const AcqRef = {
  "case_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
  "acq_id": "20260924-171200Z-ios-9c01de"
};

/** @type {import("../../../ui/types").AcqRestoreEncryptionRequest} */
export const AcqRestoreEncryptionRequest = {
  "case_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
  "acq_id": "20260924-171200Z-ios-9c01de",
  "password": "example-backup-password"
};

/** @type {import("../../../ui/types").AcqRestoreEncryptionResult} */
export const AcqRestoreEncryptionResult = {
  "restored": true,
  "will_encrypt_after": false
};

/** @type {import("../../../ui/types").OpenAcqFileRequest} */
export const OpenAcqFileRequest = {
  "case_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar",
  "acq_id": "20260924-171200Z-ios-9c01de",
  "which": "device_info"
};

/** @type {import("../../../ui/types").AcqSummary} */
export const AcqSummary = {
  "acq_id": "20260924-171200Z-ios-9c01de",
  "acq_dir": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/acquisitions/20260924-171200Z-ios-9c01de",
  "label": "Suspect iPhone 12",
  "status": "succeeded",
  "udid": "00008101-000A1B2C3D4E001E",
  "device_name": "Alex's iPhone",
  "product_version": "18.6",
  "created_at": "2026-09-24T17:12:00Z",
  "started_at": "2026-09-24T17:12:04Z",
  "ended_at": "2026-09-24T17:48:51Z",
  "duration_ms": 2211000,
  "backup_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/acquisitions/20260924-171200Z-ios-9c01de/backup/00008101-000A1B2C3D4E001E",
  "warnings": []
};

/** @type {import("../../../ui/types").AcqEvent[]} */
export const AcqEvent = [
  {
    "type": "phase",
    "phase": "backing_up"
  },
  {
    "type": "log",
    "lines": [
      "Started \"com.apple.mobilebackup2\" service on port 49324."
    ]
  },
  {
    "type": "progress",
    "percent": 45
  },
  {
    "type": "device_prompt",
    "kind": "passcode_for_encryption",
    "text": "Please confirm enabling the backup encryption by entering the passcode on the device."
  },
  {
    "type": "seal_progress",
    "files_done": 12000,
    "files_total": 48210
  },
  {
    "type": "finished",
    "status": "succeeded",
    "reasons": [],
    "warnings": [],
    "summary": {
      "acq_id": "20260924-171200Z-ios-9c01de",
      "acq_dir": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/acquisitions/20260924-171200Z-ios-9c01de",
      "label": "Suspect iPhone 12",
      "status": "succeeded",
      "udid": "00008101-000A1B2C3D4E001E",
      "device_name": "Alex's iPhone",
      "product_version": "18.6",
      "created_at": "2026-09-24T17:12:00Z",
      "started_at": "2026-09-24T17:12:04Z",
      "ended_at": "2026-09-24T17:48:51Z",
      "duration_ms": 2211000,
      "backup_path": "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar/acquisitions/20260924-171200Z-ios-9c01de/backup/00008101-000A1B2C3D4E001E",
      "warnings": []
    }
  }
];

/** @type {Record<import("../../../ui/types").ToolId, true>} */
export const ToolId = {
  "ileapp": true,
  "aleapp": true,
};

/** @type {Record<import("../../../ui/types").PlatformKey, true>} */
export const PlatformKey = {
  "macos-aarch64": true,
  "macos-x86_64": true,
  "windows-x86_64": true,
  "windows-aarch64": true,
  "linux-x86_64": true,
  "linux-aarch64": true,
};

/** @type {Record<import("../../../ui/types").InputKind, true>} */
export const InputKind = {
  "file": true,
  "directory": true,
};

/** @type {Record<import("../../../ui/types").InputType, true>} */
export const InputType = {
  "fs": true,
  "tar": true,
  "zip": true,
  "gz": true,
  "itunes": true,
  "file": true,
  "raw": true,
};

/** @type {Record<import("../../../ui/types").ModuleMode, true>} */
export const ModuleMode = {
  "all": true,
  "profile": true,
  "custom": true,
};

/** @type {Record<import("../../../ui/types").RunStatus, true>} */
export const RunStatus = {
  "running": true,
  "succeeded": true,
  "completed_with_errors": true,
  "failed": true,
  "cancelled": true,
  "interrupted": true,
};

/** @type {Record<import("../../../ui/types").HashStatus, true>} */
export const HashStatus = {
  "not_requested": true,
  "not_applicable": true,
  "pending": true,
  "completed": true,
  "cancelled": true,
  "failed": true,
  "interrupted": true,
};

/** @type {Record<import("../../../ui/types").SealStatus, true>} */
export const SealStatus = {
  "pending": true,
  "sealed": true,
  "skipped_no_output": true,
  "failed": true,
  "cancelled": true,
  "interrupted": true,
};

/** @type {Record<import("../../../ui/types").InstallSource, true>} */
export const InstallSource = {
  "download": true,
  "offline_import": true,
  "dev_override": true,
};

/** @type {Record<import("../../../ui/types").EntryVerifiedAgainst, true>} */
export const EntryVerifiedAgainst = {
  "manifest": true,
  "install_record": true,
  "none": true,
};

/** @type {Record<import("../../../ui/types").ToolState, true>} */
export const ToolState = {
  "unsupported_platform": true,
  "not_installed": true,
  "installed_unverified": true,
  "verified": true,
  "verification_failed": true,
  "dev_override": true,
};

/** @type {Record<import("../../../ui/types").RunPhase, true>} */
export const RunPhase = {
  "preparing": true,
  "running": true,
  "hashing_input": true,
  "analyzing": true,
  "sealing_report": true,
  "finalizing": true,
};

/** @type {Record<import("../../../ui/types").AcqStatus, true>} */
export const AcqStatus = {
  "running": true,
  "succeeded": true,
  "failed": true,
  "cancelled": true,
  "interrupted": true,
};

/** @type {Record<import("../../../ui/types").AcqPhase, true>} */
export const AcqPhase = {
  "preparing": true,
  "enabling_encryption": true,
  "backing_up": true,
  "restoring_encryption": true,
  "validating": true,
  "sealing": true,
  "finalizing": true,
};

/** @type {Record<import("../../../ui/types").PairState, true>} */
export const PairState = {
  "paired": true,
  "not_paired": true,
  "awaiting_trust": true,
  "locked": true,
  "trust_denied": true,
  "pairing_failed": true,
  "unknown": true,
};

/** @type {Record<import("../../../ui/types").IdeviceToolSource, true>} */
export const IdeviceToolSource = {
  "bundled": true,
  "system": true,
  "dev_override": true,
};

/** @type {Record<import("../../../ui/types").IdeviceToolsState, true>} */
export const IdeviceToolsState = {
  "ok": true,
  "missing": true,
  "verification_failed": true,
  "usbmuxd_unavailable": true,
  "unsupported_platform": true,
};

/** @type {Record<import("../../../ui/types").ToolVerification, true>} */
export const ToolVerification = {
  "manifest": true,
  "code_signature": true,
  "recorded_only": true,
  "none": true,
};

/** @type {Record<import("../../../ui/types").RestoreState, true>} */
export const RestoreState = {
  "not_requested": true,
  "restored": true,
  "failed": true,
  "not_attempted": true,
  "unknown": true,
};

/** @type {Record<import("../../../ui/types").DevicePromptKind, true>} */
export const DevicePromptKind = {
  "passcode_for_backup": true,
  "passcode_for_encryption": true,
};

/** @type {Record<import("../../../ui/types").ErrorCode, true>} */
export const ErrorCode = {
  "another_instance_running": true,
  "run_already_active": true,
  "acq_not_found": true,
  "device_busy": true,
  "already_paired": true,
  "restore_not_applicable": true,
  "path_not_supported_by_tool": true,
  "device_not_found": true,
  "device_not_paired": true,
  "device_locked": true,
  "trust_pending": true,
  "trust_denied": true,
  "pairing_failed": true,
  "usbmuxd_unavailable": true,
  "idevice_tools_missing": true,
  "idevice_tools_verification_failed": true,
  "encryption_already_on": true,
  "encryption_password_required": true,
  "insufficient_space": true,
  "run_not_found": true,
  "tool_not_installed": true,
  "tool_verification_failed": true,
  "unsupported_platform": true,
  "download_failed": true,
  "hash_mismatch": true,
  "extract_failed": true,
  "introspection_failed": true,
  "case_not_found": true,
  "case_exists": true,
  "invalid_case": true,
  "invalid_input": true,
  "input_type_not_allowed": true,
  "input_overlaps_case": true,
  "password_required": true,
  "invalid_timezone": true,
  "profile_not_found": true,
  "profile_invalid": true,
  "profile_exists": true,
  "unknown_modules": true,
  "report_missing": true,
  "path_not_allowed": true,
  "path_too_long": true,
  "permission_denied": true,
  "io": true,
  "internal": true,
};

/** @type {Record<import("../../../ui/types").HashAlgorithm, true>} */
export const HashAlgorithm = {
  "sha256": true,
};

/** @type {Record<import("../../../ui/types").InstallStage, true>} */
export const InstallStage = {
  "downloading": true,
  "verifying": true,
  "extracting": true,
  "hashing": true,
  "introspecting": true,
  "done": true,
};

/** @type {Record<import("../../../ui/types").StdStream, true>} */
export const StdStream = {
  "stdout": true,
  "stderr": true,
};

/** @type {Record<import("../../../ui/types").JobKind, true>} */
export const JobKind = {
  "run": true,
  "acquisition": true,
};

/** @type {Record<import("../../../ui/types").RunFile, true>} */
export const RunFile = {
  "stdout": true,
  "stderr": true,
  "run_json": true,
  "report_manifest": true,
};

/** @type {Record<import("../../../ui/types").AcqFile, true>} */
export const AcqFile = {
  "stdout": true,
  "stderr": true,
  "acquisition_json": true,
  "backup_manifest": true,
  "device_info": true,
};

/** @type {Record<import("../../../ui/types").PreflightLevel, true>} */
export const PreflightLevel = {
  "ok": true,
  "warn": true,
  "block": true,
};

/** @type {Record<import("../../../ui/types").AcqCommandPurpose, true>} */
export const AcqCommandPurpose = {
  "enable_encryption": true,
  "backup": true,
  "restore_encryption": true,
};

/** @type {Record<import("../../../ui/types").DeviceChangeKind, true>} */
export const DeviceChangeKind = {
  "pair_record_created": true,
  "backup_encryption_enabled": true,
  "sync_lock_taken": true,
  "backup_encryption_disabled": true,
};

/** @type {Record<import("../../../ui/types").PasswordChannel, true>} */
export const PasswordChannel = {
  "env": true,
};
