// @ts-check
// Z0c characterization (frozen: later bundles do not edit this file). The job-stream hub's bind():
// a phase event that arrives before run_start / acq_start returns (the id is not known yet) cannot
// update the store's active job; bind(id) then brings activeJob.phase up to date. Pins the
// phase-sync branch of bind() in ui/lib/jobstream.js (area-6 U8), through the public entry points
// createJobStreams() and createStore() only.
import { test } from "node:test";
import assert from "node:assert/strict";

import { createJobStreams } from "../../ui/lib/jobstream.js";
import { createStore } from "../../ui/lib/store.js";

/** @typedef {import("../../ui/lib/context").AppState} AppState */
/** @typedef {import("../../ui/types").ActiveJob} Job */

const CASE = "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar";

/** @type {Extract<Job, { kind: "run" }>} */
const RUN = {
  kind: "run",
  case_path: CASE,
  run_id: "20260924-183005Z-ileapp-3f9a1c",
  tool: "ileapp",
  created_at: "2026-09-24T18:30:05Z",
  phase: "preparing",
};

/** @type {Extract<Job, { kind: "acquisition" }>} */
const ACQ = {
  kind: "acquisition",
  case_path: CASE,
  acq_id: "20260924-171200Z-ios-9c01de",
  udid: "00008101-000A1B2C3D4E001E",
  created_at: "2026-09-24T17:12:00Z",
  phase: "preparing",
};

/** @param {Job | null} activeJob */
const storeWith = (activeJob) =>
  createStore(/** @type {AppState} */ ({ mode: "mock", appInfo: null, settings: null, tools: null, activeJob, timezones: null }));

test("z0 bind: a run's phase event before bind updates activeJob.phase once bound", () => {
  const store = storeWith(RUN);
  const jobs = createJobStreams(store);
  const b = jobs.begin("run", CASE);
  b.onEvent({ type: "phase", phase: "running" });
  // Before bind the stream has no id, so the store still has the phase job_active reported.
  assert.equal(store.get().activeJob, RUN);
  b.bind(RUN.run_id);
  const job = store.get().activeJob;
  assert.equal(job?.phase, "running");
  // The same job with only the phase changed, keys in the same order.
  assert.equal(JSON.stringify(job), JSON.stringify({ ...RUN, phase: "running" }));
  assert.equal(jobs.current()?.id, RUN.run_id);
  assert.equal(jobs.current()?.phase, "running");
});

test("z0 bind: an acquisition's phase event before bind updates activeJob.phase once bound", () => {
  const store = storeWith(ACQ);
  const jobs = createJobStreams(store);
  const b = jobs.begin("acquisition", CASE);
  b.onEvent({ type: "phase", phase: "enabling_encryption" });
  assert.equal(store.get().activeJob, ACQ);
  b.bind(ACQ.acq_id);
  const job = store.get().activeJob;
  assert.equal(job?.phase, "enabling_encryption");
  assert.equal(JSON.stringify(job), JSON.stringify({ ...ACQ, phase: "enabling_encryption" }));
  assert.equal(jobs.current()?.id, ACQ.acq_id);
});

test("z0 bind: the latest early phase wins, and later events keep the phase in sync", () => {
  const store = storeWith(RUN);
  const jobs = createJobStreams(store);
  const b = jobs.begin("run", CASE);
  b.onEvent({ type: "phase", phase: "running" });
  b.onEvent({ type: "phase", phase: "analyzing" });
  b.bind(RUN.run_id);
  assert.equal(store.get().activeJob?.phase, "analyzing");
  b.onEvent({ type: "phase", phase: "sealing_report" });
  assert.equal(store.get().activeJob?.phase, "sealing_report");
});

test("z0 bind: the active job is left alone when it is another job, already current, or no phase arrived", () => {
  // Another job is active (another id): not touched.
  {
    const other = { ...RUN, run_id: "20260924-183005Z-ileapp-000000" };
    const store = storeWith(other);
    const b = createJobStreams(store).begin("run", CASE);
    b.onEvent({ type: "phase", phase: "running" });
    b.bind(RUN.run_id);
    assert.equal(store.get().activeJob, other);
  }
  // The stored phase is already the stream's phase: the same object stays.
  {
    const running = { ...RUN, phase: /** @type {const} */ ("running") };
    const store = storeWith(running);
    const b = createJobStreams(store).begin("run", CASE);
    b.onEvent({ type: "phase", phase: "running" });
    b.bind(RUN.run_id);
    assert.equal(store.get().activeJob, running);
  }
  // No phase event before bind: nothing to bring up to date.
  {
    const store = storeWith(RUN);
    const b = createJobStreams(store).begin("run", CASE);
    b.onEvent({ type: "log", lines: ["x"] });
    b.bind(RUN.run_id);
    assert.equal(store.get().activeJob, RUN);
  }
  // No active job in the store: it stays null.
  {
    const store = storeWith(null);
    const b = createJobStreams(store).begin("run", CASE);
    b.onEvent({ type: "phase", phase: "running" });
    b.bind(RUN.run_id);
    assert.equal(store.get().activeJob, null);
  }
});
