// @ts-check
// Z0c characterization (frozen: later bundles do not edit this file or tests/ui/z0-mock-records/).
// The records the mock returns, compared as JSON text: key order is user-visible, because the Raw
// run.json and Raw acquisition.json panels show JSON.stringify(record, null, 2) (area-6 U12).
// - case_open of the seeded case (Operation Nightjar), and run_get / acq_get of each of its runs and
//   acquisitions;
// - a run per outcome and an acquisition per scenario (DEVELOPMENT.md §4.6, the mock's header),
//   each in a fresh mock instance, so no scenario depends on another's device state.
// Only the public mock functions (the names of ui/api/ipc.js) are used.
//
// Normalized (see `normalize`), and nothing else:
// - job ids `YYYYMMDD-HHMMSSZ-<kind>-<6 hex>` that the mock generates at load or run time (their
//   hex is random): the hex is numbered in order of first appearance (`#1`); the time part is
//   masked (`<now>`) only when it is from this test run. The fixed ids (the contract fixtures'
//   and the mock's literal ones) stay exact: they are the ids that two fresh mock instances seed
//   alike (`STABLE_IDS`);
// - RFC 3339 timestamps from this test run: `<iso-now>`;
// - `duration_ms` of a record created during this test run (whole seconds apart, so 0 or 1000 by
//   chance): `"<duration-ms>"`; null stays null;
// - `modules.resolved` when it is exactly every module name of `tool_modules`, sorted (the seeded
//   "All modules" runs; 1,300 names): `"<every tool_modules name, sorted>"`.
// The goldens are tests/ui/z0-mock-records/<name>.json. With Z0_ACTUAL_DIR=<dir> in the
// environment, the normalized actual texts are also written there; the test refuses to run when
// <dir> is the goldens folder.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

/** @typedef {typeof import("../../ui/api/ipc.js")} Api */
/** @typedef {import("../../ui/types").RunRequest} RunRequest */
/** @typedef {import("../../ui/types").AcqRequest} AcqRequest */
/** @typedef {import("../../ui/types").RunEvent} RunEvent */
/** @typedef {import("../../ui/types").AcqEvent} AcqEvent */
/** @typedef {import("../../ui/types").ToolId} ToolId */

/** @type {any} */ (globalThis).__SUITEDFIR_MOCK_TICK_MS = 1;

const STARTED_MS = Date.now();
/** A timestamp up to this far outside the test run counts as made during it. */
const TIME_SLACK_MS = 60_000;
const CASE = "/Users/examiner/Documents/suiteDFIR Cases/Operation Nightjar";
const EV = "/Volumes/Evidence";
const ALL_MODULES = "<every tool_modules name, sorted>";
const GOLDEN_DIR = new URL("./z0-mock-records/", import.meta.url);
const ACTUAL_DIR = /** @type {any} */ (globalThis).process?.env?.Z0_ACTUAL_DIR ?? null;

if (ACTUAL_DIR) {
  // Never write the actual texts over the goldens (the same folder by any spelling or link).
  const fs = /** @type {any} */ (await import("node:fs"));
  // (node:url is not declared in tests/ui/node.d.ts; a computed specifier is typed `any`.)
  const nodeUrl = "node:url";
  const url = await import(nodeUrl);
  const platform = /** @type {any} */ (globalThis).process?.platform;
  fs.mkdirSync(ACTUAL_DIR, { recursive: true });
  /** @param {string} p */
  const canonical = (p) => {
    const real = fs.realpathSync.native(p);
    return platform === "win32" || platform === "darwin" ? real.toLowerCase() : real;
  };
  if (canonical(ACTUAL_DIR) === canonical(url.fileURLToPath(GOLDEN_DIR))) {
    throw new Error(`Z0_ACTUAL_DIR (${ACTUAL_DIR}) is the goldens folder tests/ui/z0-mock-records/; choose another folder`);
  }
}

let instances = 0;
/**
 * A fresh mock instance (its state is per module load); no scenario flags.
 * @returns {Promise<Api>}
 */
async function freshMock() {
  instances += 1;
  return import(new URL(`../../ui-dev/mock.js?z0=${instances}`, import.meta.url).href);
}

/**
 * A fresh mock instance loaded with scenario flags (the mock reads them from `location` at load).
 * @param {string} flags
 * @returns {Promise<Api>}
 */
async function freshMockWith(flags) {
  instances += 1;
  const g = /** @type {any} */ (globalThis);
  g.location = { search: `?mock&scenario=${flags}` };
  try {
    return await import(new URL(`../../ui-dev/mock.js?z0=${instances}&flags=${flags}`, import.meta.url).href);
  } finally {
    delete g.location;
  }
}

/**
 * The job ids of every seeded case (in order).
 * @param {Api} mock
 */
async function seededIds(mock) {
  /** @type {string[]} */
  const ids = [];
  for (const summary of await mock.cases_list()) {
    if (!summary.exists) continue;
    const detail = await mock.case_open({ path: summary.path });
    ids.push(...detail.runs.map((r) => r.run_id), ...detail.acquisitions.map((a) => a.acq_id));
  }
  return ids;
}

/**
 * The fixed job ids: those that two fresh mock instances seed alike. A seeded id with random hex
 * differs between them (a 1 in 16,777,216 chance of matching).
 */
const STABLE_IDS = await (async () => {
  const a = await seededIds(await freshMock());
  const b = await seededIds(await freshMock());
  assert.equal(a.length, b.length);
  return new Set(a.filter((id, i) => id === b[i]));
})();

/**
 * @param {Api} mock
 * @param {ToolId} tool
 */
async function sortedModuleNames(mock, tool) {
  return (await mock.tool_modules({ tool })).modules.map((m) => m.name).sort();
}

/**
 * The normalized JSON text of a mock answer (see the file header).
 * @param {Api} mock
 * @param {unknown} value
 */
async function normalize(mock, value) {
  const to = Date.now() + TIME_SLACK_MS;
  /** @param {number} ms */
  const inRun = (ms) => ms >= STARTED_MS - TIME_SLACK_MS && ms <= to;
  const all = { ileapp: await sortedModuleNames(mock, "ileapp"), aleapp: await sortedModuleNames(mock, "aleapp") };
  const v = /** @type {any} */ (structuredClone(value));
  /** @param {any} rec */
  const record = (rec) => {
    if (typeof rec.created_at === "string" && inRun(Date.parse(rec.created_at)) && typeof rec.duration_ms === "number") {
      rec.duration_ms = "<duration-ms>";
    }
    const tool = /** @type {ToolId | undefined} */ (rec.tool?.id);
    const resolved = rec.modules?.resolved;
    if (tool && Array.isArray(resolved) && JSON.stringify(resolved) === JSON.stringify(all[tool])) rec.modules.resolved = ALL_MODULES;
  };
  if (Array.isArray(v.runs)) {
    for (const r of v.runs) record(r);
    for (const a of v.acquisitions) record(a);
  } else {
    record(v);
  }
  /** @type {Map<string, number>} */
  const hexes = new Map();
  return `${JSON.stringify(v, null, 2)}\n`
    .replace(/\b(\d{4})(\d{2})(\d{2})-(\d{2})(\d{2})(\d{2})Z-(ileapp|aleapp|ios)-([0-9a-f]{6})\b/g, (m, y, mo, d, h, mi, s, kind, hex) => {
      if (STABLE_IDS.has(m)) return m;
      const stamp = inRun(Date.UTC(+y, +mo - 1, +d, +h, +mi, +s)) ? "<now>" : `${y}${mo}${d}-${h}${mi}${s}Z`;
      if (!hexes.has(hex)) hexes.set(hex, hexes.size + 1);
      return `${stamp}-${kind}-#${hexes.get(hex)}`;
    })
    .replace(/\b(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?Z/g, (m, y, mo, d, h, mi, s) =>
      inRun(Date.UTC(+y, +mo - 1, +d, +h, +mi, +s)) ? "<iso-now>" : m,
    );
}

/**
 * Compares the normalized text of `value` with the golden `<name>.json`.
 * @param {Api} mock
 * @param {string} name
 * @param {unknown} value
 */
async function snapshot(mock, name, value) {
  const actual = await normalize(mock, value);
  if (ACTUAL_DIR) {
    const fs = /** @type {any} */ (await import("node:fs"));
    fs.mkdirSync(ACTUAL_DIR, { recursive: true });
    fs.writeFileSync(`${ACTUAL_DIR}/${name}.json`, actual);
  }
  /** @type {string | null} */
  let golden = null;
  try {
    golden = readFileSync(new URL(`${name}.json`, GOLDEN_DIR), "utf8");
  } catch {
    golden = null;
  }
  assert.equal(actual, golden, `the normalized mock answer differs from tests/ui/z0-mock-records/${name}.json`);
}

/**
 * Starts a job and resolves once `finished` arrived and no job is active.
 * @template {RunEvent | AcqEvent} E
 * @param {Api} mock
 * @param {(onEvent: (e: E) => void) => Promise<string>} start Resolves with the job id.
 * @param {(id: string, events: E[]) => Promise<void>} [during]
 */
async function jobToEnd(mock, start, during) {
  /** @type {E[]} */
  const events = [];
  /** @type {() => void} */
  let done = () => {};
  const finished = new Promise((resolve) => {
    done = () => resolve(undefined);
  });
  const id = await start((e) => {
    events.push(e);
    if (e.type === "finished") done();
  });
  if (during) await during(id, events);
  await finished;
  await idle(mock);
  return id;
}

/**
 * Resolves once no job is active.
 * @param {Api} mock
 */
async function idle(mock) {
  while (await mock.job_active()) await sleep(2);
}

/** @param {number} ms */
const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/**
 * @template T
 * @param {T[]} events
 * @param {(e: T) => boolean} pred
 */
async function until(events, pred) {
  while (!events.some(pred)) await sleep(2);
}

// ---- The seeded case ----

const seed = await freshMock();
const seedDetail = await seed.case_open({ path: CASE });

test("z0 mock records: seed-case-open", async () => {
  await snapshot(seed, "seed-case-open", seedDetail);
});

for (const [i, run] of seedDetail.runs.entries()) {
  const name = `seed-run-${i + 1}-${run.status}`;
  test(`z0 mock records: ${name}`, async () => {
    await snapshot(seed, name, await seed.run_get({ case_path: CASE, run_id: run.run_id }));
  });
}

for (const [i, acq] of seedDetail.acquisitions.entries()) {
  const name = `seed-acq-${i + 1}-${acq.status}`;
  test(`z0 mock records: ${name}`, async () => {
    await snapshot(seed, name, await seed.acq_get({ case_path: CASE, acq_id: acq.acq_id }));
  });
}

// ---- One run per outcome ----

/**
 * @param {Partial<RunRequest>} o
 * @returns {RunRequest}
 */
const runRequest = (o) => ({
  case_path: CASE,
  tool: "ileapp",
  input_path: `${EV}/Pixel-7-extraction`,
  input_type: "fs",
  modules: { mode: "all" },
  timezone: "UTC",
  itunes_password: null,
  keychain_path: null,
  hash_input: false,
  label: null,
  ...o,
});

/**
 * @param {Api} mock
 * @param {ToolId} tool
 * @returns {Promise<import("../../ui/types").ModuleSelection>}
 */
async function threeModules(mock, tool) {
  const names = (await mock.tool_modules({ tool })).modules.slice(0, 3).map((m) => m.name);
  return { mode: "custom", modules: names };
}

/** @type {[string, (mock: Api) => Promise<RunRequest>, "cancel" | "interrupt" | null][]} */
const RUNS = [
  ["run-succeeded-all-modules", async () => runRequest({ label: "Full file system" }), null],
  [
    "run-succeeded-hashed-file",
    async (mock) =>
      runRequest({
        input_path: `${EV}/iPhone-12-FFS.zip`,
        input_type: "zip",
        modules: await threeModules(mock, "ileapp"),
        hash_input: true,
        label: "Hashed image",
      }),
    null,
  ],
  [
    "run-succeeded-itunes-password-profile",
    async () =>
      runRequest({
        input_path: `${EV}/00008101-000A1B2C3D4E`,
        input_type: "itunes",
        modules: { mode: "profile", profile_name: "Quick triage" },
        itunes_password: "examiner-secret",
        label: "Encrypted backup",
      }),
    null,
  ],
  [
    "run-succeeded-aleapp",
    async (mock) =>
      runRequest({ tool: "aleapp", input_path: `${EV}/Pixel-7.tar`, input_type: "tar", modules: await threeModules(mock, "aleapp"), timezone: null, hash_input: true }),
    null,
  ],
  ["run-completed-with-errors", async (mock) => runRequest({ input_path: `${EV}/errors`, modules: await threeModules(mock, "ileapp") }), null],
  ["run-failed-invalid", async (mock) => runRequest({ input_path: `${EV}/fail-invalid`, modules: await threeModules(mock, "ileapp") }), null],
  ["run-failed-early", async (mock) => runRequest({ input_path: `${EV}/fail-early`, modules: await threeModules(mock, "ileapp") }), null],
  ["run-failed-argparse", async (mock) => runRequest({ input_path: `${EV}/fail-argparse`, modules: await threeModules(mock, "ileapp") }), null],
  ["run-failed-crash", async (mock) => runRequest({ input_path: `${EV}/fail-crash`, modules: await threeModules(mock, "ileapp") }), null],
  ["run-cancelled", async (mock) => runRequest({ input_path: `${EV}/slow`, modules: await threeModules(mock, "ileapp") }), "cancel"],
  ["run-interrupted", async (mock) => runRequest({ input_path: `${EV}/interrupt`, modules: await threeModules(mock, "ileapp") }), "interrupt"],
];

for (const [name, request, how] of RUNS) {
  test(`z0 mock records: ${name}`, async () => {
    const mock = await freshMock();
    const req = await request(mock);
    /** @type {string} */
    let runId;
    if (how === "interrupt") {
      runId = (await mock.run_start(req, () => {})).run_id;
      await idle(mock);
      const detail = await mock.case_open({ path: CASE });
      assert.deepEqual(detail.recovered, [runId]);
    } else {
      runId = await jobToEnd(
        mock,
        /** @param {(e: RunEvent) => void} onEvent */ async (onEvent) => (await mock.run_start(req, onEvent)).run_id,
        how === "cancel"
          ? async (id, events) => {
              await until(events, (e) => e.type === "log");
              await mock.run_cancel({ run_id: id });
            }
          : undefined,
      );
    }
    await snapshot(mock, name, await mock.run_get({ case_path: CASE, run_id: runId }));
  });
}

// ---- One acquisition per scenario ----

/**
 * @param {Api} mock
 * @param {string} label
 * @param {boolean} encrypt
 * @param {boolean} [restore]
 * @returns {Promise<AcqRequest>}
 */
async function acqRequest(mock, label, encrypt, restore = encrypt) {
  const { devices } = await mock.devices_list();
  return {
    case_path: CASE,
    udid: devices[0].udid,
    label,
    enable_encryption: encrypt,
    encryption_password: encrypt ? "examiner-pw" : null,
    restore_encryption: restore,
  };
}

/** @type {[string, (mock: Api) => Promise<AcqRequest>, "cancel" | "interrupt" | null][]} */
const ACQS = [
  ["acq-succeeded", (mock) => acqRequest(mock, "Seized iPhone, item 7", false), null],
  ["acq-succeeded-encrypted", (mock) => acqRequest(mock, "Seized iPhone, item 7", true), null],
  ["acq-succeeded-encryption-kept-on", (mock) => acqRequest(mock, "Seized iPhone, item 7", true, false), null],
  ["acq-backup-fail", (mock) => acqRequest(mock, "Seized iPhone, item 7/backup_fail", false), null],
  ["acq-enable-fail", (mock) => acqRequest(mock, "Seized iPhone, item 7/enable_fail", true), null],
  ["acq-restore-fail", (mock) => acqRequest(mock, "Seized iPhone, item 7/restore_fail", true), null],
  ["acq-incomplete", (mock) => acqRequest(mock, "Seized iPhone, item 7/incomplete", false), null],
  ["acq-cancel-on-device", (mock) => acqRequest(mock, "Seized iPhone, item 7/cancel_on_device", false), null],
  ["acq-disconnect", (mock) => acqRequest(mock, "Seized iPhone, item 7/disconnect", true), null],
  ["acq-sync-lock", (mock) => acqRequest(mock, "Seized iPhone, item 7/sync_lock", false), null],
  ["acq-cancelled", (mock) => acqRequest(mock, "Seized iPhone, item 7/slow", false), "cancel"],
  ["acq-interrupted", (mock) => acqRequest(mock, "Seized iPhone, item 7/interrupt", true), "interrupt"],
];

for (const [name, request, how] of ACQS) {
  test(`z0 mock records: ${name}`, async () => {
    const mock = await freshMock();
    const req = await request(mock);
    /** @type {string} */
    let acqId;
    if (how === "interrupt") {
      acqId = (await mock.acq_start(req, () => {})).acq_id;
      await idle(mock);
      const detail = await mock.case_open({ path: CASE });
      assert.deepEqual(detail.recovered, [acqId]);
    } else {
      acqId = await jobToEnd(
        mock,
        /** @param {(e: AcqEvent) => void} onEvent */ async (onEvent) => (await mock.acq_start(req, onEvent)).acq_id,
        how === "cancel"
          ? async (id, events) => {
              await until(events, (e) => e.type === "progress");
              await mock.acq_cancel({ acq_id: id });
            }
          : undefined,
      );
    }
    await snapshot(mock, name, await mock.acq_get({ case_path: CASE, acq_id: acqId }));
  });
}

// An acquisition cancelled while sealing (`hold_sealing` keeps it there until the cancel): the
// backup finished, so the seal is cancelled and `seal_cancelled` is a warning (ui-dev/mock.js).
test("z0 mock records: acq-cancelled-while-sealing", async () => {
  const mock = await freshMockWith("hold_sealing");
  const req = await acqRequest(mock, "Seized iPhone, item 7", false);
  const acqId = await jobToEnd(
    mock,
    /** @param {(e: AcqEvent) => void} onEvent */ async (onEvent) => (await mock.acq_start(req, onEvent)).acq_id,
    async (id, events) => {
      await until(events, (e) => e.type === "seal_progress");
      await mock.acq_cancel({ acq_id: id });
    },
  );
  await snapshot(mock, "acq-cancelled-while-sealing", await mock.acq_get({ case_path: CASE, acq_id: acqId }));
});
