//! Repository maintenance tasks, run as `cargo xtask <command>` (alias in `.cargo/config.toml`).
//!
//! The other commands listed in DEVELOPMENT.md §2 are added by their roadmap tasks.

mod idevice_tools;

use std::fs;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use suitedfir_core::contracts::examples::{self, Fixture};

const USAGE: &str = "usage: cargo xtask <command>

commands:
  contracts   regenerate ui-dev/fixtures/contracts/ from the Rust contract examples
  fetch-idevice-tools [--target <triple>]
              fetch and verify the pinned libimobiledevice tools into src-tauri/binaries/";

const FIXTURES_DIR: &str = "ui-dev/fixtures/contracts";

fn main() -> ExitCode {
    match std::env::args().nth(1).as_deref() {
        Some("help" | "-h" | "--help") => {
            println!("{USAGE}");
            ExitCode::SUCCESS
        }
        Some("contracts") => match contracts(&repo_root().join(FIXTURES_DIR)) {
            Ok(summary) => {
                println!("{summary}");
                ExitCode::SUCCESS
            }
            Err(e) => {
                eprintln!("xtask contracts: {e}");
                ExitCode::FAILURE
            }
        },
        Some("fetch-idevice-tools") => idevice_tools::run(&repo_root()),
        Some(other) => {
            eprintln!("unknown command: {other}\n\n{USAGE}");
            ExitCode::from(2)
        }
        None => {
            eprintln!("{USAGE}");
            ExitCode::from(2)
        }
    }
}

fn repo_root() -> PathBuf {
    let xtask_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    xtask_dir.parent().unwrap_or(xtask_dir).to_path_buf()
}

/// Writes one `<Type>.json` per fixture plus `index.js`, and removes any other file in `dir`, so
/// the directory mirrors the Rust examples exactly. Files whose content is unchanged are not
/// rewritten; running it twice changes nothing.
fn contracts(dir: &Path) -> Result<String, String> {
    let fixtures = examples::fixtures().map_err(|e| e.to_string())?;
    fs::create_dir_all(dir).map_err(|e| format!("creating {}: {e}", dir.display()))?;

    let mut wanted = vec![("index.js".to_owned(), index_js(&fixtures)?)];
    wanted.extend(
        fixtures
            .iter()
            .map(|f| (format!("{}.json", f.name), f.text.clone())),
    );

    let mut written = 0;
    for (name, content) in &wanted {
        let path = dir.join(name);
        if fs::read_to_string(&path).ok().as_deref() != Some(content.as_str()) {
            fs::write(&path, content).map_err(|e| format!("writing {}: {e}", path.display()))?;
            written += 1;
        }
    }
    let mut removed = 0;
    let entries = fs::read_dir(dir).map_err(|e| format!("listing {}: {e}", dir.display()))?;
    for entry in entries {
        let entry = entry.map_err(|e| format!("listing {}: {e}", dir.display()))?;
        let name = entry.file_name().to_string_lossy().into_owned();
        if !wanted.iter().any(|(wanted, _)| *wanted == name) {
            fs::remove_file(entry.path())
                .map_err(|e| format!("removing stale {}: {e}", entry.path().display()))?;
            removed += 1;
        }
    }
    Ok(format!(
        "{FIXTURES_DIR}: {} files ({written} written, {removed} removed)",
        wanted.len()
    ))
}

/// The fixtures the UI sees, as an ES module. The app's CSP (`connect-src` has no `'self'`) blocks
/// fetching JSON in browser mock mode, so `ui-dev/mock.js` imports this instead. Each export is
/// annotated with its `ui/types.d.ts` type, so `npm run typecheck` checks the examples against the
/// TypeScript types; enums are exported as `{ value: true }` records so the check is exact.
fn index_js(fixtures: &[Fixture]) -> Result<String, String> {
    let mut out = String::from(
        "// @ts-check\n\
         // Generated by `cargo xtask contracts` from crates/core/src/contracts/examples.rs; do not edit.\n\
         // The fixtures of ui/types.d.ts types as an ES module (the *.json files are the same data).\n\
         // Enums are exported as { value: true } records, so tsc checks them against the unions exactly.\n",
    );
    for f in fixtures {
        let Some(ts) = &f.ts_type else { continue };
        let types = "import(\"../../../ui/types\")";
        out.push('\n');
        if f.is_enum {
            let values: Vec<serde_json::Value> =
                serde_json::from_str(&f.text).map_err(|e| format!("{}: {e}", f.name))?;
            out.push_str(&format!("/** @type {{Record<{types}.{ts}, true>}} */\n"));
            out.push_str(&format!("export const {} = {{\n", f.name));
            for value in values {
                out.push_str(&format!("  {value}: true,\n"));
            }
            out.push_str("};\n");
        } else {
            out.push_str(&format!("/** @type {{{types}.{ts}}} */\n"));
            out.push_str(&format!("export const {} = {}", f.name, f.text.trim_end()));
            out.push_str(";\n");
        }
    }
    Ok(out)
}
