//! Z0a2 characterizations for S-TOOL (SIMPLIFY.md §3): the exact `AppError`s that candidates S2
//! and S3 move or inline, pinned through entry points no candidate removes (`Jobs::reserve`,
//! `Installs::begin` and the `AppState` command methods).
//!
//! - S3: `run_already_active` from `Jobs::reserve` while the slot is reserved or held, and from
//!   `run_start`, `acq_start` and `temp_cleanup` while a run is active; what `Installs::begin`
//!   returns (it refuses only a second install of the same tool; the job slot does not stop it).
//! - S2: a manifest without an aLEAPP entry: `tool_status` (with and without the dev override),
//!   `tools_status`, `tool_install`, `tool_modules` and `run_start` say "The tool manifest has no
//!   entry for aleapp"; `input_inspect` and `profiles_list` say "Unknown tool".
//!
//! Expected errors are written out here. The helpers are this module's own (never the private
//! ones of `ops/tests.rs` or `replay.rs`). Frozen: later bundles do not edit this file
//! (SIMPLIFY.md §2).

use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use suitedfir_core::contracts::{
    AcqRequest, AppError, CaseCreateRequest, ErrorCode, InputInspectRequest, InputType,
    ModuleSelection, RunCancelRequest, RunEvent, RunRequest, RunStatus, Timestamp, ToolId,
    examples,
};
use suitedfir_core::manifest;

use crate::ops::InstallFrom;
use crate::state::{Installs, Job, JobHandle, Jobs, Subscriber};
use crate::testing::{self, Lab, LabOptions};

/// How long a cancelled run may take to finish.
const WAIT: Duration = Duration::from_secs(90);
const RUN_ID: &str = "20260924-183005Z-ileapp-3f9a1c";
/// A device id (fake-idevice's); no test here reaches the device.
const UDID: &str = "00008101-000A1B2C3D4E001E";

/// `run_already_active`, as a second job start gets it.
fn already_active() -> AppError {
    AppError {
        code: ErrorCode::RunAlreadyActive,
        message: "Another job is running. Wait for it to finish or cancel it.".to_owned(),
        detail: None,
    }
}

/// `temp_cleanup` while a job, an install or a device command runs.
fn cleanup_refused() -> AppError {
    AppError {
        code: ErrorCode::RunAlreadyActive,
        message: "Temporary files cannot be cleaned while a job, a parser installation or a \
                  device command is running"
            .to_owned(),
        detail: None,
    }
}

fn install_running(display_name: &str) -> AppError {
    AppError {
        code: ErrorCode::RunAlreadyActive,
        message: format!("{display_name} is already being installed."),
        detail: None,
    }
}

fn case_in(lab: &Lab) -> PathBuf {
    let fields = examples::case_fields();
    let detail = lab
        .state
        .case_create(&CaseCreateRequest {
            name: fields.name,
            case_number: fields.case_number,
            examiner: fields.examiner,
            agency: fields.agency,
            description: fields.description,
            default_timezone: fields.default_timezone,
            parent_dir: None,
        })
        .unwrap();
    PathBuf::from(detail.path)
}

fn input_in(lab: &Lab) -> PathBuf {
    let dir = lab.root.path().join("ev").join("fs");
    fs::create_dir_all(&dir).unwrap();
    fs::write(dir.join("evidence.txt"), "evidence").unwrap();
    dir
}

fn run_request(tool: ToolId, case: &Path, input: &Path) -> RunRequest {
    RunRequest {
        case_path: case.to_string_lossy().into_owned(),
        tool,
        input_path: input.to_string_lossy().into_owned(),
        input_type: InputType::Fs,
        modules: ModuleSelection::All,
        timezone: None,
        itunes_password: None,
        keychain_path: None,
        hash_input: false,
        label: None,
    }
}

fn acq_request(case: &Path) -> AcqRequest {
    AcqRequest {
        case_path: case.to_string_lossy().into_owned(),
        udid: UDID.to_owned(),
        label: None,
        enable_encryption: false,
        encryption_password: None,
        restore_encryption: true,
    }
}

/// Runs of this lab use fake-leapp's `scenario`.
fn use_scenario(lab: &Lab, scenario: &str) {
    let mut env = lab.state.leapp_env.lock().unwrap();
    env.retain(|(name, _)| name != "FAKE_LEAPP_SCENARIO");
    env.push(("FAKE_LEAPP_SCENARIO".into(), scenario.into()));
}

/// A run subscriber that keeps every event.
fn recorder() -> (Subscriber<RunEvent>, Arc<Mutex<Vec<RunEvent>>>) {
    let events = Arc::new(Mutex::new(Vec::new()));
    let sink = Arc::clone(&events);
    (
        Box::new(move |event: &RunEvent| sink.lock().unwrap().push(event.clone())),
        events,
    )
}

fn ignore<E: 'static>() -> Subscriber<E> {
    Box::new(|_: &E| {})
}

/// Waits for the run's `finished` event (the slot is freed just before it is sent).
fn wait_for_finished(events: &Mutex<Vec<RunEvent>>) -> RunStatus {
    let deadline = Instant::now() + WAIT;
    loop {
        let status = events.lock().unwrap().iter().find_map(|event| match event {
            RunEvent::Finished { status, .. } => Some(*status),
            _ => None,
        });
        if let Some(status) = status {
            return status;
        }
        assert!(Instant::now() < deadline, "no finished event");
        std::thread::sleep(Duration::from_millis(20));
    }
}

// ---- S3: the one job slot and the installs ----

/// `Jobs::reserve` while the slot is reserved (for a run or a device) or holds an active job.
#[test]
fn z0_a_second_reservation_is_run_already_active() {
    let jobs = Jobs::default();
    let first = jobs.reserve(None).unwrap();
    assert_eq!(jobs.reserve(None).err(), Some(already_active()));
    assert_eq!(
        jobs.reserve(Some(UDID.to_owned())).err(),
        Some(already_active())
    );
    drop(first);
    let device = jobs.reserve(Some(UDID.to_owned())).unwrap();
    assert_eq!(jobs.reserve(None).err(), Some(already_active()));
    device.activate(Job {
        id: RUN_ID.to_owned(),
        case_path: "case".to_owned(),
        created_at: Timestamp::now(),
        handle: JobHandle::Restore {
            udid: UDID.to_owned(),
        },
    });
    assert_eq!(jobs.reserve(None).err(), Some(already_active()));
    jobs.finish(RUN_ID);
    assert!(jobs.reserve(None).is_ok());
}

/// `Installs::begin` refuses only a second install of the same tool (with the display name it is
/// given); another tool, or a taken job slot, does not stop it.
#[test]
fn z0_installs_begin_refuses_only_the_same_tool() {
    let installs = Installs::default();
    let ileapp = installs.begin(ToolId::Ileapp, "iLEAPP").unwrap();
    assert_eq!(
        installs.begin(ToolId::Ileapp, "iLEAPP").err(),
        Some(install_running("iLEAPP"))
    );
    assert_eq!(
        installs.begin(ToolId::Ileapp, "Some Name").err(),
        Some(install_running("Some Name"))
    );
    let aleapp = installs.begin(ToolId::Aleapp, "aLEAPP").unwrap();
    assert_eq!(
        installs.begin(ToolId::Aleapp, "aLEAPP").err(),
        Some(install_running("aLEAPP"))
    );
    drop((ileapp, aleapp));

    // Through the app state: the job slot does not matter; `tool_install` names the tool as the
    // manifest does (refused before anything is downloaded).
    let lab = testing::lab_state();
    let state = &lab.state;
    let reservation = state.jobs.reserve(None).unwrap();
    let held = state.installs.begin(ToolId::Ileapp, "iLEAPP").unwrap();
    let mut events = Vec::new();
    assert_eq!(
        state
            .tool_install(ToolId::Ileapp, InstallFrom::Download, &mut |event| {
                events.push(event)
            })
            .unwrap_err(),
        install_running("iLEAPP")
    );
    assert!(events.is_empty(), "{events:?}");
    assert_eq!(state.temp_cleanup().unwrap_err(), cleanup_refused());
    drop(reservation);
    // Only the install is running now.
    assert_eq!(state.temp_cleanup().unwrap_err(), cleanup_refused());
    drop(held);
}

/// While a run is active: a second run, an acquisition, `temp_cleanup` and a reservation are
/// refused with exact errors and create nothing; an install may still begin.
#[test]
fn z0_job_starts_while_a_run_is_active() {
    let lab = testing::lab_state();
    let state = &lab.state;
    let case = case_in(&lab);
    let input = input_in(&lab);
    use_scenario(&lab, "slow");
    let (subscriber, events) = recorder();
    let run = state
        .run_start(run_request(ToolId::Ileapp, &case, &input), subscriber)
        .unwrap();
    assert_eq!(
        state
            .run_start(run_request(ToolId::Ileapp, &case, &input), ignore())
            .unwrap_err(),
        already_active()
    );
    assert_eq!(
        state
            .run_start(run_request(ToolId::Aleapp, &case, &input), ignore())
            .unwrap_err(),
        already_active()
    );
    assert_eq!(
        state.acq_start(acq_request(&case), ignore()).unwrap_err(),
        already_active()
    );
    assert_eq!(state.temp_cleanup().unwrap_err(), cleanup_refused());
    assert_eq!(state.jobs.reserve(None).err(), Some(already_active()));
    assert_eq!(fs::read_dir(case.join("runs")).unwrap().count(), 1);
    assert!(!case.join("acquisitions").exists());
    assert!(state.installs.begin(ToolId::Aleapp, "aLEAPP").is_ok());

    state
        .run_cancel(&RunCancelRequest {
            run_id: run.run_id.clone(),
        })
        .unwrap();
    assert_eq!(wait_for_finished(&events), RunStatus::Cancelled);
    assert!(state.jobs.wait_idle(Some(WAIT)));
    assert!(state.jobs.reserve(None).is_ok());
}

// ---- S2: a manifest without an aLEAPP entry ----

fn manifest_without_aleapp() -> suitedfir_core::contracts::LeappManifest {
    let mut manifest = manifest::embedded().unwrap().clone();
    assert!(manifest.tools.remove(&ToolId::Aleapp).is_some());
    manifest
}

fn no_entry() -> AppError {
    AppError {
        code: ErrorCode::Internal,
        message: "The tool manifest has no entry for aleapp".to_owned(),
        detail: None,
    }
}

fn unknown_tool() -> AppError {
    AppError {
        code: ErrorCode::Internal,
        message: "Unknown tool".to_owned(),
        detail: Some("aleapp".to_owned()),
    }
}

/// aLEAPP without the dev override (iLEAPP keeps it): every command that needs aLEAPP's pinned
/// entry fails with the exact error of its path, and a refused `run_start` creates nothing and
/// frees the slot.
#[test]
fn z0_a_manifest_without_aleapp() {
    let lab = testing::lab(LabOptions {
        leapp_override: vec![ToolId::Ileapp],
        manifest: manifest_without_aleapp(),
        ..LabOptions::default()
    });
    let state = &lab.state;
    let case = case_in(&lab);
    let input = input_in(&lab);

    assert_eq!(
        state.tool_status(ToolId::Aleapp, false).unwrap_err(),
        no_entry()
    );
    assert_eq!(
        state.tool_status(ToolId::Aleapp, true).unwrap_err(),
        no_entry()
    );
    assert_eq!(state.tools_status().unwrap_err(), no_entry());
    let mut events = Vec::new();
    assert_eq!(
        state
            .tool_install(ToolId::Aleapp, InstallFrom::Download, &mut |event| {
                events.push(event)
            })
            .unwrap_err(),
        no_entry()
    );
    assert!(events.is_empty(), "{events:?}");
    assert!(state.installs.begin(ToolId::Aleapp, "aLEAPP").is_ok());
    assert_eq!(state.tool_modules(ToolId::Aleapp).unwrap_err(), no_entry());
    assert_eq!(
        state
            .run_start(run_request(ToolId::Aleapp, &case, &input), ignore())
            .unwrap_err(),
        no_entry()
    );
    assert!(!case.join("runs").exists());
    assert!(state.jobs.reserve(None).is_ok());
    assert_eq!(
        state
            .input_inspect(&InputInspectRequest {
                tool: ToolId::Aleapp,
                path: input.to_string_lossy().into_owned(),
                case_path: case.to_string_lossy().into_owned(),
            })
            .unwrap_err(),
        unknown_tool()
    );
    assert_eq!(
        state.profiles_list(ToolId::Aleapp).unwrap_err(),
        unknown_tool()
    );

    // iLEAPP is unaffected.
    assert!(state.tool_status(ToolId::Ileapp, false).is_ok());
    assert!(state.profiles_list(ToolId::Ileapp).is_ok());
}

/// The same manifest with aLEAPP under the dev override: `tool_status` and `run_start` fail with
/// the same error (the override's path looks the manifest up too).
#[test]
fn z0_a_manifest_without_aleapp_under_the_dev_override() {
    let lab = testing::lab(LabOptions {
        manifest: manifest_without_aleapp(),
        ..LabOptions::default()
    });
    let state = &lab.state;
    let case = case_in(&lab);
    let input = input_in(&lab);
    assert_eq!(
        state.tool_status(ToolId::Aleapp, false).unwrap_err(),
        no_entry()
    );
    assert_eq!(state.tools_status().unwrap_err(), no_entry());
    assert_eq!(
        state
            .run_start(run_request(ToolId::Aleapp, &case, &input), ignore())
            .unwrap_err(),
        no_entry()
    );
    assert!(!case.join("runs").exists());
    assert!(state.jobs.reserve(None).is_ok());
}
